### ISSUE TITLE
搜索不到本地安装的python sdk，同时希望改进交互。有点不好用。

### ISSUE THREAD

**Issue by yudar1024** [gvcgo/version-manager#105]
## Platform Info

windows
## Description

1. 交互有点反直觉，在搜索python的时候，下面的快捷键会变更，并不知道当前处于一种什么样的交互状态
2. 在搜索本地是否有安装python的时候，本地是有安装的，通过python exe 安装，但反馈没有搜到
3. 即使没有搜到，也不希望退出整个进程，但是现在的结果是，一旦没有找到，就退出整个竞争，要重新vmr才能又开始。又要走一遍搜索。

**Comment by moqsien** [comment]
首先，vmr不能管理通过其他渠道安装的SDK，任何其他版本管理器应该也是这样，大家的实现原理差不多。
其次，vmr所有快捷键提示是根据下一步可能需要的操作进行显示的。在版本列表获得焦点时，会有返回上一步的快捷键，不一定非要退出。
最后，对于这方面有疑惑的，建议读一下文档，理解一下vmr的TUI，所有关于TUI的设计都是为了尽量减少用户输入，同时不要界面太复杂。

**Comment by BleethNie** [comment]
tui 感觉操作感觉有些难受，特别是在安装软件安装失败的情况下，我会多次尝试重复安装软件，这个时候就必须经过

**Comment by moqsien** [comment]
> tui 感觉操作感觉有些难受，特别是在安装软件安装失败的情况下，我会多次尝试重复安装软件，这个时候就必须经过如下步骤：
> 
> 1. vmr
> 2. 搜索sdk名称 如go
> 3. enter
> 4. 搜索go版本如1.22.6
> 5. enter确认
>    未考虑部分自动化场景，很多sdk写到脚本里实现自动化安装

不能因为一个点而否定TUI整体效率更高的事实。

VMR以前是命令行模式，在很多用户的强烈推荐下，逐渐改成TUI模式。
事实上，VMR管理的SDK不止有go这种拼写简单的SDK，还有llvm-mingw, git-for-windows等拼写比较长，甚至有一些用户不熟悉但非常好用的SDK或工具。用户大部分时候需要先查看VMR支持哪些SDK，甚至SDK的名字可能与惯用名称有一定区别，例如gxx表示g++等等。在找到SDK名称后，就可能要知道有哪些可以安装的版本，进而进行安装。因为很多SDK的版本号不一样，甚至很长，这种TUI联动的方式，能进一步减少这种输入。

虽然失去了历史命令直接上下翻的这种便捷，但是TUI在整体上是减少了用户输入的。一直反复安装同一SDK的各种不同版本的情况是占少数的，因此使用历史命令的场景也是少数。
