### ISSUE TITLE
thrift未配置环境变量path

### ISSUE THREAD

**Issue by lzp4ever** [gvcgo/version-manager#107]
thrift.exe位置：thrift-compiler\Library\bin

**Comment by moqsien** [comment]
注意读文档：
1. [快捷键](https://vdocs.vmr.us.kg/zh-cn/guides/tutorial/#%E5%8F%AF%E5%AE%89%E8%A3%85%E7%89%88%E6%9C%AC%E5%88%97%E8%A1%A8%E7%9B%B8%E5%85%B3%E7%9A%84%E5%BF%AB%E6%8D%B7%E6%8C%89%E9%94%AE%E6%8F%90%E7%A4%BA)
2. [安装模式](https://vdocs.vmr.us.kg/zh-cn/starts/concepts/#%E5%AE%89%E8%A3%85%E6%A8%A1%E5%BC%8F)
3. [常见问题](https://vdocs.vmr.us.kg/zh-cn/guides/faq/#%E5%88%9B%E5%BB%BA%E7%9B%AE%E5%BD%95%E7%9A%84%E8%BD%AF%E9%93%BE%E6%8E%A5%E5%A4%B1%E8%B4%A5)
