### ISSUE TITLE
被杀毒了

### ISSUE THREAD

**Issue by heliye-sy** [gvcgo/version-manager#11]
![beishadu](https://github.com/gvcgo/version-manager/assets/131220411/19b94855-ac9e-4e46-9a96-09a6301d9e9d)

**Comment by moqsien** [comment]
go跨平台编译的exe文件容易被360等误认为病毒之类的，这个暂时没有好的办法。

看你是什么杀毒软件，手动从release下载安装后，设置杀毒软件为信任即可。

**Comment by moqsien** [comment]
或者你是gopher，也可以尝试自行编译代码。

**Comment by moqsien** [comment]
具体解释参考：
https://v2ex.com/t/948678

**Comment by moqsien** [comment]
已用UPX压缩套壳，在作者Win11机器上测试通过。
有时间可以测试一下。
windows-amd64版本。如果可行，以后新版本都会加壳。
