### ISSUE TITLE
添加 wasmtime 

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#113]
https://docs.wasmtime.dev/cli-install.html

https://github.com/bytecodealliance/wasmtime/releases

**Comment by moqsien** [comment]
有github release的尽量把release贴出来。
只有官网下载页面的，把官网下载页面(含历史版本)贴出来。
这样可以减少维护组的工作。

另外，如果自己有go开发能力，可以尝试阅读[Vcolletor](https://github.com/gvcgo/vcollector)代码，贡献你想要的SDK相关的爬虫。

**Comment by Avey777** [comment]
> 有github release的尽量把release贴出来。 只有官网下载页面的，把官网下载页面(含历史版本)贴出来。 这样可以减少维护组的工作。
> 
> 另外，如果自己有go开发能力，可以尝试阅读[Vcolletor](https://github.com/gvcgo/vcollector)代码，贡献你想要的SDK相关的爬虫。

https://github.com/bytecodealliance/wasmtime/releases

**Comment by moqsien** [comment]
已实现。
