### ISSUE TITLE
受不了, 太难用了,  还是CLI 简单易用

### ISSUE THREAD

**Issue by Super1Windcloud** [gvcgo/version-manager#116]

**Comment by Super1Windcloud** [comment]
推荐个 scoop  reset , 版本切换非常好用  ,   vfox也不错

**Comment by Avey777** [comment]
> 推荐个 scoop reset , 版本切换非常好用 , vfox也不错

之前比较好用，采用这种方式的同时。 去掉了之前 cli 的部分功能，导致在配置一些自动化的时候不友好
建议两种方式都要支持，不同的场景下有不同的需求

**Comment by moqsien** [comment]
> > 推荐个 scoop reset , 版本切换非常好用 , vfox也不错
> 
> 之前比较好用，采用这种方式的同时。 去掉了之前 cli 的部分功能，导致在配置一些自动化的时候不友好 建议两种方式都要支持，不同的场景下有不同的需求

暂时没时间弄这个。
有时间和兴趣，会go的同学可以尝试提PR，实现自己需要的CLI功能。

**Comment by Avey777** [comment]
![image](https://github.com/user-attachments/assets/3c70fe92-b363-4240-9f0d-de37012c89d2)
vfox 远不如 vmr 支持的插件多，等后面支持了 CLI  就完美了

**Comment by moqsien** [comment]
已实现。
