### ISSUE TITLE
Incorrect installation of rustup

### ISSUE THREAD

**Issue by Haif-07** [gvcgo/version-manager#119]
![image](https://github.com/user-attachments/assets/302a7951-3c66-4341-93a2-767a5224edd8)
![image](https://github.com/user-attachments/assets/a69813fd-286a-499a-b706-15d8150b05dd)

Its size is 480k, but the actual download size from the official website is 8.5m

Directly installing the rust version will cause vscode to not use rust-analyzer, but this is not your fault.
It seems that using vmr to manage rust is not a good solution

**Comment by moqsien** [comment]
Thanks for your issue.
This is a bug from the VMR installer for executables.
It will be fixed later.
