### ISSUE TITLE
mac在安装后没有自动添加环境变量

### ISSUE THREAD

**Issue by ghostzhang** [gvcgo/version-manager#12]
执行
`curl --proto '=https' --tlsv1.2 -sSf https://gvc.1710717.xyz/proxy/https://raw.githubusercontent.com/gvcgo/version-manager/main/scripts/install.sh | sh`
后环境变量没有添加到系统中，需要手动添加

**Comment by moqsien** [comment]
你使用的是bash，zsh还是fish？

vmr安装的时候，会自动检测shell类型，bash会向.bashrc，zsh会向.zshrc，fish会向.config/fish/config.fish中写入
```bash
# vm_envs start
if [ -z $VM_DISABLE ]; then
    . /Users/moqsien/.vm/vm_env.sh
fi
# vm_envs end
```

mac下，以我自己的情况为例，会自动写入.zshrc，使用source .zshrc即可使环境变量生效。

**Comment by ghostzhang** [comment]
在 .zshrc 中看到了
