### ISSUE TITLE
vmr 查看本地安装的 sdk 命令

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#122]
目前的 vmr local sdk-name 只能查看已安装的 sdk 的版本， 如果 vmr local  可以展示所有已经有安装的 sdk 名词就好了

**Comment by moqsien** [comment]
可以尝试贡献代码！

**Comment by Avey777** [comment]
> 可以尝试贡献代码！

我对这个没有思路，go 这边只会写一些简单的 api

**Comment by moqsien** [comment]
> > 可以尝试贡献代码！
> 
> 我对这个没有思路，go 这边只会写一些简单的 api

慢慢就熟悉了。这是开源项目，不着急的。

**Comment by moqsien** [comment]
> 使用vmr可以将已经安装过的sdk路径添加吗?注意这里指的不是通过vmr进行安装的

不能。据我了解，目前所有的版本管理器都不支持不通过自己安装的SDK。这是原理决定的。

**Comment by moqsien** [comment]
Added in [v0.7.0](https://github.com/gvcgo/version-manager/releases/tag/v0.7.0).
