### ISSUE TITLE
Support pnpm?

### ISSUE THREAD

**Issue by bycgxss** [gvcgo/version-manager#125]

**Comment by moqsien** [comment]
you can search pnpm using 'vmr search -c pnpm'.

Then install pnpm through conda. But you need to add Envs manually to vmr.sh.

**Comment by moqsien** [comment]
![pnpm](https://github.com/user-attachments/assets/64761c2c-7155-4dac-9e8b-c30fe15ce3ad)

**Comment by bycgxss** [comment]
Thanks!
