### ISSUE TITLE
交互感觉有点问题

### ISSUE THREAD

**Issue by snail2sky** [gvcgo/version-manager#126]
## Description

1. 当前已经是类似tui的方式，通过交互来搜索sdk，然后还要退出去根据sdk名字在搜索版本，然后在退出去，进行安装，如果能直接层级的找下去，按回车安装就好多了，不然我都不知道交互有啥用，进去选择好我需要安装的sdk和版本，结果按半天回车发现没有回车这个功能。。。，不知道是不是我的操作问题还是本来就没有这个功能
2. 
![test](https://github.com/user-attachments/assets/f96e8d3f-2aab-43a5-93f3-de7dfe25ae65)

**Comment by snail2sky** [comment]
做成 类似 tui 的目标可能就是为了可以方便用户，一个命令就能搞定所有的事情，但是目前需要三次进入tui，然后才能完成sdk的安装

**Comment by snail2sky** [comment]
期望的交互效果
1. 命令行输入 vmr 进入vmr tui界面
2. 输入安装的 sdk 或 工具名后，找到自己想要安装的工具并选择，然后回车
3. 直接进入到当前工具版本选择界面，选择自己期望安装的版本，然后回车
4. 直接进行安装

**Comment by snail2sky** [comment]
另外 还有 vmr local 这种命令，这种如果没给任何参数的话，最好也是直接进入tui，然后直接显示已有的 sdk或工具 
甚至都可以不要这个子命令，直接就用一个vmr命令就完事，反正安装的目的就是为了使用，所以直接通过 vmr 这一个命令来调整 sdk的某一个版本即可

**Comment by moqsien** [comment]
你显然没有认真看过TUI界面的按键提示。
也没有认真去读过文档。

这么明显的问题，很显然不可能有的。

[TUI界面快捷键文档](https://vdocs.vmr.us.kg/zh-cn/guides/tutorial/#%E5%8F%AF%E5%AE%89%E8%A3%85%E7%89%88%E6%9C%AC%E5%88%97%E8%A1%A8%E7%9B%B8%E5%85%B3%E7%9A%84%E5%BF%AB%E6%8D%B7%E6%8C%89%E9%94%AE%E6%8F%90%E7%A4%BA)

**Comment by moqsien** [comment]
不需要科学上网，直接打开就行。

而且TUI界面的英文提示很简单。基本也不用看文档。

**Comment by snail2sky** [comment]
好吧 按s 键，大佬直接用 回车键不是更加方便吗，现在回车键都没啥用处，回车 空格键都非常好，可以当个别名来用，反正目前 vmr 也支持别名

**Comment by snail2sky** [comment]
可能 公司把 你这个域名ban了，访问不了~

**Comment by snail2sky** [comment]
现在回车键跟 tab 键的功能好像是重叠的

**Comment by moqsien** [comment]
因为你在输入框输入完成就是按enter切换焦点的。
如果再把enter绑到搜索和安装，这就有点莫名其妙了。以英文字母做快捷键，且界面上有提示，这更清晰。

**Comment by snail2sky** [comment]
是的，直接切换焦点到列表选择页，可以选择所有的可用版本
反正我作为用户我肯定是更想用回车~，因为右手一个手就能搞定，方便得很，主要回车键也大~
刚才马马虎虎的看了一眼界面提示，就没仔细看，然后就不知道有这个功能
之前听过一句话叫 好的产品不需要说明书，而且如果不看说明的话，估计大多数人肯定都是喜欢直接按回车
还是希望大佬能加上回车就能进入下级页面这个功能 十分感谢 [合十][合十]

**Comment by snail2sky** [comment]
嗯嗯  好的
