### ISSUE TITLE
提供非交互式命令&支持json输出

### ISSUE THREAD

**Issue by kaizi2009** [gvcgo/version-manager#129]
### 原因：
1. 非交互式的安装命令，便于分享，分享场景如：入职指引文档、项目的README.md文档、wiki、社区等；
2. 便于运维人员编写shell脚本；
3. 便于在dockerfile中编写命令。

### 方案建议
1. 所有场景都提供非交互式命令；
2. 输出结果支持json，增加--json参数。
原因：
-  json便于传递和分享
- 结构化的json数据便于用户二次开发，如：在运维脚本中动态选择版本
- 基于非交互式命令、json输出格式，可以进一步的开发桌面应用，更好的管理sdk版本、项目的sdk版本

**Comment by kaizi2009** [comment]
随着docker的发展，生产环境安装sdk的场景大多数都是docker，我想在dockerfile中使用vmr的安装命令，但vmr的安装是交互式的

**Comment by moqsien** [comment]
生产环境的话，比如JDK你肯定是直接用dockerhub上的镜像，而不是自己从空容器开始打包。

VMR设计的初衷，就是不想用臃肿的容器来进行版本管理。回到容器属于是倒退了。

**Comment by kaizi2009** [comment]
1、有的容器可能同时需要jdk, node, python；
2、基于容器对项目进行打包也是趋势，可能同时需要jdk, node, python，git环境。
如：基于jdk的官方镜像，再安装一下node, python，git

**Comment by moqsien** [comment]
> 1、有的容器可能同时需要jdk, node, python； 2、基于容器对项目进行打包也是趋势，可能同时需要jdk, node, python，git环境。 如：基于jdk的官方镜像，再安装一下node, python，git

可以用多个镜像打包啊，只不过docker file会麻烦一点。

而且，如果是同时起node，java, python项目，还不如分别打包到不同镜像，然后用docker-compose管理，这样更清晰。

所有的打包到一个镜像，我个人还真没遇见过，哈哈。

**Comment by kaizi2009** [comment]
安装目前只能是交互式的吧？不利于安装命令的分享

**Comment by kaizi2009** [comment]
vmr的稳定性，在于sdk的稳定性，一旦sdk安装成功，就跟vmr没有关系了，只要sdk是长期支持版本就行

**Comment by moqsien** [comment]
> https://vdocs.vmr.us.kg/zh-cn/guides/cli/

命令行文档：https://vdocs.vmr.us.kg/zh-cn/guides/cli/
同时支持TUI和命令行。
