### ISSUE TITLE
执行 vmr install-self 后，vmr文件被删除

### ISSUE THREAD

**Issue by ghostzhang** [gvcgo/version-manager#13]
![image](https://github.com/gvcgo/version-manager/assets/194242/00a4f918-0b74-4cd2-b0be-8fe2ef4c1a42)

![image](https://github.com/gvcgo/version-manager/assets/194242/df37beb9-3c7f-4d50-b462-2e058ff545c5)

**Comment by moqsien** [comment]
https://v2ex.com/t/948678

跟go程序编译生成的exe文件在windows下被杀毒误报有关。

Windows-amd64版本已经启用了UPX压缩套壳，测试了一下在我的Win11虚拟机上不会误报了。可以重新试一下，Report一下结果。
特别感谢。

**Comment by ghostzhang** [comment]
忘了说是mac系统

**Comment by moqsien** [comment]
哦，明白问题在哪里了。

已经在安装目录的vmr，如果使用vmr install-self命令，它会先把自己删除，然后试图复制自己到安装目录的时候已经找不到了。

这里忘了考虑这种判断了。还得是用户反馈，不然很难意识到这点。
加个判断就行，对于已经安装的vmr，install-self不做任何操作就行了。

**Comment by moqsien** [comment]
已修复。
