### ISSUE TITLE
cocoapods不可用！

### ISSUE THREAD

**Issue by bycgxss** [gvcgo/version-manager#131]
安装ruby@3.3.6，并使用```gem install cocoapods```，显示安装成功
<img width="1288" alt="截屏2024-11-16 17 35 55" src="https://github.com/user-attachments/assets/090c9107-027c-49d0-b532-fc9a3ae7344a">
但是查看pod时报错！

**Comment by moqsien** [comment]
ruby不熟悉。
盲猜跟环境变量有关。你可以找找跟ruby和cocoapods有关的环境变量的资料。

**Comment by bycgxss** [comment]
貌似是电脑问题，我在我的m2 MacBook Air上是没有问题的
