### ISSUE TITLE
Failed to install bun 1.1.38 on mac os arm64

### ISSUE THREAD

**Issue by wodeguaiguai** [gvcgo/version-manager#133]
## Platform Info
MacOS arm64

## Description
Failed to install bun 1.1.38. The downloaded compressed file contains two folders, Unable to extract the compressed package into the version folder.

## Screen Shot

![image](https://github.com/user-attachments/assets/b1da8e7c-4dd5-4331-98f8-4dff2ec5260f)
![image](https://github.com/user-attachments/assets/b41a93f8-4263-4452-a113-664a261dc1b1)

**Comment by moqsien** [comment]
I do not have an arm64 MacOS available, however, it's not  likely to be with the problem of containing two folders as VMR will find the right folder to copy.

Would you please show more detailed info for the installation failures?

**Comment by wodeguaiguai** [comment]
![image](https://github.com/user-attachments/assets/61d2d9c7-4a80-4400-b90f-e2ca5b2eacae)
I think the __MACOSX folder should be ignored.

**Comment by wodeguaiguai** [comment]
#134
