### ISSUE TITLE
关于 local 指令

### ISSUE THREAD

**Issue by lokistars** [gvcgo/version-manager#136]
## Platform Info

MacOS arm64

## Description

1. 使用 vmr local 时候必须要指定sdk name 例如：vmr local rustup
2. 是否可以直接通过var local 列出所有安装的sdk列表， 而不需要指定 skd name

**Comment by lokistars** [comment]
可以使用 vmr in 命令查看当前安装的sdk ， 但是无法显示安装的版本

**Comment by moqsien** [comment]
所以，是想要vmr in和vmr local的结合是吧。

晚一点吧，加个命令就好。

其实，更推荐使用TUI，在TUI下面，有快捷按键提示，不用命令行那么麻烦。

**Comment by moqsien** [comment]
![vmr_ii](https://github.com/user-attachments/assets/bd54cd3e-9141-4b79-8241-686261563fcf)

已实现，新版v0.7.1，新增vmr ii命令，可以一键显示本地所有通过vmr安装的SDK以及版本。

**Comment by lokistars** [comment]
这个快捷键特别不喜欢,  基本隔一段时间没使用就会忘记,  为什么不用 list 呢, 例如 brew list
