### ISSUE TITLE
安装与卸载脚本各种报错，windows与linux命令混用，window下只能使用powershell终端环境？

### ISSUE THREAD

**Issue by izdbrave** [gvcgo/version-manager#138]

**Comment by moqsien** [comment]
你说的报错，是指安装和卸载SDK还是安装和卸载vmr本身？

还有，希望提供详细信息，才能判断是什么问题。

此外，可以先读一下文档https://vdocs.vmr.us.kg/zh-cn/starts/quickstart/，看看使用上是不是存在问题。

至于windows和linux命令混用，可能是指zig和upx特别处理的两个bug。稍后修复。

**Comment by izdbrave** [comment]
windows下使用git bash安装
![image](https://github.com/user-attachments/assets/a5f5810c-4c53-4d76-b65f-1e20a9ae5b7b)
windows下使用cmd卸载
![image](https://github.com/user-attachments/assets/7a75c9f6-b7cb-4fec-96fa-5d058f72078d)
windows下使用git bash安装依赖
![image](https://github.com/user-attachments/assets/158d3abb-c1c8-44e8-bd33-40339c06efdd)

**Comment by moqsien** [comment]
> windows下使用git bash安装 ![image](https://private-user-images.githubusercontent.com/16437804/398500547-a5f5810c-4c53-4d76-b65f-1e20a9ae5b7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTQxMjYsIm5iZiI6MTczNTA5MzgyNiwicGF0aCI6Ii8xNjQzNzgwNC8zOTg1MDA1NDctYTVmNTgxMGMtNGM1My00ZDc2LWI2NWYtMWUyMGE5YWU1YjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ODdhMmY0NDlhZGNmMWMwMmZhNjIyNjk2MWExOTZiN2Y5MWJiZjliODYyODA0NTlkZjY1YWQxZDkwNjhiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iaRkfoHFJpvLvLLRocmuZvC-6_KBNTlAzO6b0VicggA) windows下使用cmd卸载 ![image](https://private-user-images.githubusercontent.com/16437804/398500058-7a75c9f6-b7cb-4fec-96fa-5d058f72078d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTQxMjYsIm5iZiI6MTczNTA5MzgyNiwicGF0aCI6Ii8xNjQzNzgwNC8zOTg1MDAwNTgtN2E3NWM5ZjYtYjdjYi00ZmVjLTk2ZmEtNWQwNThmNzIwNzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOWMwYjUwNWE5Yjc3ZGU5N2NlNGVlMzAxZGQxYjhmY2QwZmMzZTZhN2EwOGQ2YTY3MTEzMDc2Y2ZhZmQ2NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sorqJ1J0JaszQpmdpgeWwJY12UkfWBexjGVWx7ZmX70) windows下使用git bash安装依赖 ![image](https://private-user-images.githubusercontent.com/16437804/398500776-158d3abb-c1c8-44e8-bd33-40339c06efdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTQxMjYsIm5iZiI6MTczNTA5MzgyNiwicGF0aCI6Ii8xNjQzNzgwNC8zOTg1MDA3NzYtMTU4ZDNhYmItYzFjOC00NGU4LWJkMzMtNDAzMzljMDZlZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OGE4MjhkZTVjYWZmYTYxYjA3MzQ5ZTg1Njc3ZjVhNTc0Mjg1ZjgwNTg1NzNjY2Q5OGJkN2ZjNzMzNDBjN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.95-ttDaHlJUTh6EnNCfie8PaVx2WiwgXceF1rKhpA3M)

你在mingw的bash shell里面安装windows版本，当然读不到windows相关的系统命令了。
mingw环境没有专门测试过。建议使用powershell。

**Comment by izdbrave** [comment]
至少第二张图我在cmd下卸载是报错的，另外不应该强制依赖于某个终端环境，这完全可以从代码层面解决，用过这么多工具第一次遇到在git bash下不兼容，我第一反应是软件有bug，又在powershell下试了才可以，希望能考虑解决

**Comment by moqsien** [comment]
> 至少第二张图我在cmd下卸载是报错的，另外不应该强制依赖于某个终端环境，这完全可以从代码层面解决，用过这么多工具第一次遇到在git bash下不兼容，我第一反应是软件有bug，又在powershell下试了才可以，希望能考虑解决

https://github.com/gvcgo/version-manager/releases/tag/v0.7.2

新发了个版，支持了windows下的mingw bash shell。

可以在mingw shell内正常安装SDK，更新和卸载VMR。

**Comment by moqsien** [comment]
开源不易，留下star，可以帮忙推荐给同事、好友使用。

**Comment by izdbrave** [comment]
> 开源不易，留下star，可以帮忙推荐给同事、好友使用。

简直太赞！

**Comment by moqsien** [comment]
> > 开源不易，留下star，可以帮忙推荐给同事、好友使用。
> 
> 简直太赞！

可以安利给自己周围的同事和朋友，帮助VMR推广。

VMR支持的SDK数量，可扩展性(通过Conda)，易用性(同时支持TUI界面和命令行)，跨平台，都是其他SDK版本管理器比不了的。

之所以比vfox star少，是因为晚了2个月，没有被hellogithub推广。
