### ISSUE TITLE
goplus安装后在zsh中找不到gop命令

### ISSUE THREAD

**Issue by yongyuanfan** [gvcgo/version-manager#139]
1. 已经全局安装goplus

 goplus installed versions
─────────────────────────────────────────
 1.2.6<current>

2. 在goplus-versions也有软连接
<img width="557" alt="image" src="https://github.com/user-attachments/assets/c5c48641-4e29-45da-b1d9-c9eca2f13256" />

3. 在终端执行过source ~/.zshrc，但是提示gop命令找不到

**Comment by moqsien** [comment]
> 1. 已经全局安装goplus
> 
> goplus installed versions ───────────────────────────────────────── 1.2.6
> 
> 2. 在goplus-versions也有软连接
> 
> <img alt="image" width="557" src="https://private-user-images.githubusercontent.com/7666348/399266816-c5c48641-4e29-45da-b1d9-c9eca2f13256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTQzODAsIm5iZiI6MTczNTU1NDA4MCwicGF0aCI6Ii83NjY2MzQ4LzM5OTI2NjgxNi1jNWM0ODY0MS00ZTI5LTQ1ZGEtYjFkOS1jOWVjYTJmMTMyNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzBUMTAyMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMzNmM3OWI4YzQ2MTYzZTM2NDljNjlmZmJhYWFhNzZhYmJkNjIwOTY2ZTU4MmI0NDU1MWI4ZDJiMWExNWViMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pbOFuU-s0LgtxyfZ9K9P85RUvGKOhzYEVDcS0gmzJqA">
> 3. 在终端执行过source ~/.zshrc，但是提示gop命令找不到

请注意是否使用Global Mode（全局模式）进行安装。在TUI下面，全局模式安装的按键是i，session模式安装的按键是s。
session模式下的Path环境变量是不会持久化的，所以session退出之后就没了。重新按i安装，即可持久化Path环境变量。

**Comment by moqsien** [comment]
可以在~/.vmr/vmr.sh中查看goplus的PATH环境变量是否添加到vmr.sh文件。如果有环境变量，那么可以查看gop的可执行权限。

**Comment by yongyuanfan** [comment]
> > 1. 已经全局安装goplus
> > 
> > goplus installed versions ───────────────────────────────────────── 1.2.6
> > 
> > 2. 在goplus-versions也有软连接
> > 
> > <img alt="image" width="557" src="https://private-user-images.githubusercontent.com/7666348/399266816-c5c48641-4e29-45da-b1d9-c9eca2f13256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTQzODAsIm5iZiI6MTczNTU1NDA4MCwicGF0aCI6Ii83NjY2MzQ4LzM5OTI2NjgxNi1jNWM0ODY0MS00ZTI5LTQ1ZGEtYjFkOS1jOWVjYTJmMTMyNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzBUMTAyMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMzNmM3OWI4YzQ2MTYzZTM2NDljNjlmZmJhYWFhNzZhYmJkNjIwOTY2ZTU4MmI0NDU1MWI4ZDJiMWExNWViMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pbOFuU-s0LgtxyfZ9K9P85RUvGKOhzYEVDcS0gmzJqA">
> > 3. 在终端执行过source ~/.zshrc，但是提示gop命令找不到
> 
> 请注意是否使用Global Mode（全局模式）进行安装。在TUI下面，全局模式安装的按键是i，session模式安装的按键是s。 session模式下的Path环境变量是不会持久化的，所以session退出之后就没了。重新按i安装，即可持久化Path环境变量。
----------
我确定是全局安全的，我把terminal关闭后再打开,gop命令仍然找不到，尝试把原版本卸载后重新使用i安装，souce以后仍然不行。

**Comment by moqsien** [comment]
> > > 1. 已经全局安装goplus
> > > 
> > > goplus installed versions ───────────────────────────────────────── 1.2.6
> > > 
> > > 2. 在goplus-versions也有软连接
> > > 
> > > <img alt="image" width="557" src="https://private-user-images.githubusercontent.com/7666348/399266816-c5c48641-4e29-45da-b1d9-c9eca2f13256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTQzODAsIm5iZiI6MTczNTU1NDA4MCwicGF0aCI6Ii83NjY2MzQ4LzM5OTI2NjgxNi1jNWM0ODY0MS00ZTI5LTQ1ZGEtYjFkOS1jOWVjYTJmMTMyNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzBUMTAyMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMzNmM3OWI4YzQ2MTYzZTM2NDljNjlmZmJhYWFhNzZhYmJkNjIwOTY2ZTU4MmI0NDU1MWI4ZDJiMWExNWViMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pbOFuU-s0LgtxyfZ9K9P85RUvGKOhzYEVDcS0gmzJqA">
> > > 3. 在终端执行过source ~/.zshrc，但是提示gop命令找不到
> > 
> > 
> > 请注意是否使用Global Mode（全局模式）进行安装。在TUI下面，全局模式安装的按键是i，session模式安装的按键是s。 session模式下的Path环境变量是不会持久化的，所以session退出之后就没了。重新按i安装，即可持久化Path环境变量。
> 
> 我确定是全局安全的，我把terminal关闭后再打开,gop命令仍然找不到，尝试把原版本卸载后重新使用i安装，souce以后仍然不行。

1、进入gop的安装目录，看看你安装的gop是不是可以执行。
2、去~/.vmr/vmr.sh文件，看看gop所在的目录是否通过export PATH=$PATH:xxx添加到环境变量。
3、你的mac是arm64还是amd64的？

我现在没有mac环境。你需要提供足够的信息，这样才能判断问题出在什么地方。

**Comment by yongyuanfan** [comment]
> > > > 1. 已经全局安装goplus
> > > > 
> > > > goplus installed versions ───────────────────────────────────────── 1.2.6
> > > > 
> > > > 2. 在goplus-versions也有软连接
> > > > 
> > > > <img alt="image" width="557" src="https://private-user-images.githubusercontent.com/7666348/399266816-c5c48641-4e29-45da-b1d9-c9eca2f13256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTQzODAsIm5iZiI6MTczNTU1NDA4MCwicGF0aCI6Ii83NjY2MzQ4LzM5OTI2NjgxNi1jNWM0ODY0MS00ZTI5LTQ1ZGEtYjFkOS1jOWVjYTJmMTMyNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzBUMTAyMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMzNmM3OWI4YzQ2MTYzZTM2NDljNjlmZmJhYWFhNzZhYmJkNjIwOTY2ZTU4MmI0NDU1MWI4ZDJiMWExNWViMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pbOFuU-s0LgtxyfZ9K9P85RUvGKOhzYEVDcS0gmzJqA">
> > > > 3. 在终端执行过source ~/.zshrc，但是提示gop命令找不到
> > > 
> > > 
> > > 请注意是否使用Global Mode（全局模式）进行安装。在TUI下面，全局模式安装的按键是i，session模式安装的按键是s。 session模式下的Path环境变量是不会持久化的，所以session退出之后就没了。重新按i安装，即可持久化Path环境变量。
> > 
> > 
> > 我确定是全局安全的，我把terminal关闭后再打开,gop命令仍然找不到，尝试把原版本卸载后重新使用i安装，souce以后仍然不行。
> 
> 1、进入gop的安装目录，看看你安装的gop是不是可以执行。 2、去~/.vmr/vmr.sh文件，看看gop所在的目录是否通过export PATH=$PATH:xxx添加到环境变量。 3、你的mac是arm64还是amd64的？
> 
> 我现在没有mac环境。你需要提供足够的信息，这样才能判断问题出在什么地方。

--------
我排查了一下，是因为$VM_DISABLE这个变量的值为111所以在source的时候被跳过了，直接source .vmr/vmr.sh就没问题了，请问这个变量应该怎么管理？

**Comment by moqsien** [comment]
> > > > > 1. 已经全局安装goplus
> > > > > 
> > > > > goplus installed versions ───────────────────────────────────────── 1.2.6
> > > > > 
> > > > > 2. 在goplus-versions也有软连接
> > > > > 
> > > > > <img alt="image" width="557" src="https://private-user-images.githubusercontent.com/7666348/399266816-c5c48641-4e29-45da-b1d9-c9eca2f13256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTQzODAsIm5iZiI6MTczNTU1NDA4MCwicGF0aCI6Ii83NjY2MzQ4LzM5OTI2NjgxNi1jNWM0ODY0MS00ZTI5LTQ1ZGEtYjFkOS1jOWVjYTJmMTMyNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzBUMTAyMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMzNmM3OWI4YzQ2MTYzZTM2NDljNjlmZmJhYWFhNzZhYmJkNjIwOTY2ZTU4MmI0NDU1MWI4ZDJiMWExNWViMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pbOFuU-s0LgtxyfZ9K9P85RUvGKOhzYEVDcS0gmzJqA">
> > > > > 3. 在终端执行过source ~/.zshrc，但是提示gop命令找不到
> > > > 
> > > > 
> > > > 请注意是否使用Global Mode（全局模式）进行安装。在TUI下面，全局模式安装的按键是i，session模式安装的按键是s。 session模式下的Path环境变量是不会持久化的，所以session退出之后就没了。重新按i安装，即可持久化Path环境变量。
> > > 
> > > 
> > > 我确定是全局安全的，我把terminal关闭后再打开,gop命令仍然找不到，尝试把原版本卸载后重新使用i安装，souce以后仍然不行。
> > 
> > 
> > 1、进入gop的安装目录，看看你安装的gop是不是可以执行。 2、去~/.vmr/vmr.sh文件，看看gop所在的目录是否通过export PATH=$PATH:xxx添加到环境变量。 3、你的mac是arm64还是amd64的？
> > 我现在没有mac环境。你需要提供足够的信息，这样才能判断问题出在什么地方。
> 
> 我排查了一下，是因为$VM_DISABLE这个变量的值为111所以在source的时候被跳过了，直接source .vmr/vmr.sh就没问题了，请问这个变量应该怎么管理？

那应该是你的terminal处于session模式，一直没有关闭。所以$VM_DISABLE一直处于激活状态。

1、你可以使用exit退出session模式，然后再尝试source；
2、你也可以在.zshrc中定义alias szsh="export VM_DISABLE='' && source ~/.zshrc"

**Comment by moqsien** [comment]
更新了一下v0.7.3，新增了一个命令is-session-mode，可以用于查看当前shell 是否处于session模式。
另外，自动在shell的profile中增加一个alias svmr，通过svmr可以让在session模式下的shell中通过全局安装方式安装的sdk的环境变量生效。

但是，vmr不推荐shell一层层嵌套，session模式的shell应该及时通过exit命令退出。或者直接关闭terminal之后session模式也会退出。

**Comment by moqsien** [comment]
> > 更新了一下v0.7.3，新增了一个命令is-session-mode，可以用于查看当前shell 是否处于session模式。 另外，自动在shell的profile中增加一个alias svmr，通过svmr可以让在session模式下的shell中通过全局安装方式安装的sdk的环境变量生效。
> > https://github.com/gvcgo/version-manager/releases/tag/v0.7.3
> > 但是，vmr不推荐shell一层层嵌套，session模式的shell应该及时通过exit命令退出。或者直接关闭terminal之后session模式也会退出。
> > ![vmr_ism](https://github.com/user-attachments/assets/45d57acf-cffb-4c7c-9772-40df21636b08)
> 
> 我发现IDEA的终端默认是session模式
> 
> ![Image](https://github.com/user-attachments/assets/c607389c-be4f-45ba-8c49-2e4b7263c78c)
> 
> 也没找到相关设置可以更改，所以原来安装好的软件，在IDEA的终端中会发现找不到，所以这就导致其他终端都是正常可用的，而到了IDEA中就无法使用的情况

应该是你对该项目锁定了版本。每次打开IDEA终端的时候，会自动开启一个session并切换到锁定版本。这种是正常的。

**Comment by moqsien** [comment]
> > > > 更新了一下v0.7.3，新增了一个命令is-session-mode，可以用于查看当前shell 是否处于session模式。 另外，自动在shell的profile中增加一个alias svmr，通过svmr可以让在session模式下的shell中通过全局安装方式安装的sdk的环境变量生效。
> > > > https://github.com/gvcgo/version-manager/releases/tag/v0.7.3
> > > > 但是，vmr不推荐shell一层层嵌套，session模式的shell应该及时通过exit命令退出。或者直接关闭terminal之后session模式也会退出。
> > > > ![vmr_ism](https://github.com/user-attachments/assets/45d57acf-cffb-4c7c-9772-40df21636b08)
> > > 
> > > 
> > > 我发现IDEA的终端默认是session模式
> > > ![Image](https://github.com/user-attachments/assets/c607389c-be4f-45ba-8c49-2e4b7263c78c)
> > > 也没找到相关设置可以更改，所以原来安装好的软件，在IDEA的终端中会发现找不到，所以这就导致其他终端都是正常可用的，而到了IDEA中就无法使用的情况
> > 
> > 
> > 应该是你对该项目锁定了版本。每次打开IDEA终端的时候，会自动开启一个session并切换到锁定版本。这种是正常的。
> 
> ![Image](https://github.com/user-attachments/assets/8adbcbe6-bb64-4ed4-a68b-1b41e45088d5)
> 
> 你说的是 `.vmr.lock` 文件吗？若是因为这个文件那为何在该session终端内却找不到锁定软件版本呢？
> 
> ![Image](https://github.com/user-attachments/assets/1ed5642b-491e-4e34-8f70-d61c31880c82)


逻辑是这样的：

只有当你切换到包含.vmr.lock的目录或者子目录下面时，vmr才会自动帮你开启新的session，并把相应版本的环境变量加入这个session。

你使用IDEA终端时，这个终端会自动切换到该文件夹下，自然就处于session模式了。

你使用其他终端时，如果不是自动或者手动切换到该文件夹下，自然也就不是session模式了。
