### ISSUE TITLE
关于给每个项目独立设置nodejs版本问题

### ISSUE THREAD

**Issue by 1xiaofeng1** [gvcgo/version-manager#14]
您好，想请教下，version-manager是否可以像vfox那样单独给每一个项目设置对应的nodejs版本？如果可以，需要如何设置呢？在命令帮助里没有看到，希望指导一下，谢谢

**Comment by moqsien** [comment]
> 您好，想请教下，version-manager是否可以像vfox那样单独给每一个项目设置对应的nodejs版本？如果可以，需要如何设置呢？在命令帮助里没有看到，希望指导一下，谢谢

看了一下vfox的源码。就是新开一个终端进程，在进程中获取dir信息，然后进行切换。这个功能使用场景是什么？

在一个终端session中，不同项目目录，使用不同版本进行执行或者编译？

**Comment by moqsien** [comment]
算了，感觉没必要。如果都要输入命令，不能减少命令的个数，就不能带来实质的便利。还不如维持简洁，session模式就足以覆盖project模式了。

**Comment by 1xiaofeng1** [comment]
不好意思，这几天有点忙，没看到，刚看到消息，vfox是可以通过powershell进入对应项目文件夹，然后通过vfox -p ***@***.***这个命令设置这个项目是node的哪个版本，这样下次再打开项目的时候，node就会自动切换到这个版本，不需要自己再输入任何命令切换
----- 原始邮件 -----
发件人：moqsien ***@***.***>
收件人：gvcgo/version-manager ***@***.***>
抄送人：1xiaofeng1 ***@***.***>,  Author ***@***.***>
主题：Re:_[gvcgo/version-manager]_关于给每个项目独立设置nodejs版本问题_(Issue_#14)
日期：2024年04月12日 13点48分


算了，感觉没必要。如果都要输入命令，不能减少命令的个数，就不能带来实质的便利。还不如维持简洁，session模式就足以覆盖project模式了。

**Comment by moqsien** [comment]
> 不好意思，这几天有点忙，没看到，刚看到消息，vfox是可以通过powershell进入对应项目文件夹，然后通过vfox -p ***@***.***这个命令设置这个项目是node的哪个版本，这样下次再打开项目的时候，node就会自动切换到这个版本，不需要自己再输入任何命令切换 ----- 原始邮件 ----- 发件人：moqsien ***@***.***> 收件人：gvcgo/version-manager ***@***.***> 抄送人：1xiaofeng1 ***@***.***>, Author ***@***.***> 主题：Re:_[gvcgo/version-manager]_关于给每个项目独立设置nodejs版本问题_(Issue_#14) 日期：2024年04月12日 13点48分 算了，感觉没必要。如果都要输入命令，不能减少命令的个数，就不能带来实质的便利。还不如维持简洁，session模式就足以覆盖project模式了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

看了vfox的源码，就是不管三七二十一，上来就创建一个新的shell进程，把要切换的版本路径添加到新的shell进程作为环境变量。这样做的一个坏处就是，如果你不断切换，最终shell进程会一层套一层，光浪费系统资源，啥也没做。

vmr的设计不是这样的，默认不创建新的shell，也不希望出现一层套一层的shell进程，这对有洁癖的人来说有点难受。而且，你要监控current working dir(cwd)的变化，势必要监控用户每次在终端中的输入，然后触发获取cwd与已缓存的各种目录做对比的操作，从而决定是否再使用另外版本的路径作为环境变量开启一个新的shell进程，这实际上也或多或少影响着用户在终端的输入回显速度，虽然可能大多数时候体验不那么明显。

基于这些考虑，不建议这样做。但是我们可以考虑怎么针对项目需要，在减少输入的情况下，快速的使用session模式激活某个版本。例如，可以记住某个本地文件夹曾经在session模式使用过的版本，下载在该文件夹下，就无需输入sdk@版本号，直接**vmr use -s**即可。

这样，既可以减少冗长的输入。也不至于让shell进程一层层嵌套。

**Comment by 1xiaofeng1** [comment]
好的，明白了，谢谢您的解答
----- 原始邮件 -----
发件人：moqsien ***@***.***>
收件人：gvcgo/version-manager ***@***.***>
抄送人：1xiaofeng1 ***@***.***>,  Author ***@***.***>
主题：Re:_[gvcgo/version-manager]_关于给每个项目独立设置nodejs版本问题_(Issue_#14)
日期：2024年04月13日 09点22分



不好意思，这几天有点忙，没看到，刚看到消息，vfox是可以通过powershell进入对应项目文件夹，然后通过vfox -p @.这个命令设置这个项目是node的哪个版本，这样下次再打开项目的时候，node就会自动切换到这个版本，不需要自己再输入任何命令切换 ----- 原始邮件 ----- 发件人：moqsien @.> 收件人：gvcgo/version-manager @.> 抄送人：1xiaofeng1 @.>, Author @.> 主题：Re:[gvcgo/version-manager]关于给每个项目独立设置nodejs版本问题(Issue#14) 日期：2024年04月12日 13点48分 算了，感觉没必要。如果都要输入命令，不能减少命令的个数，就不能带来实质的便利。还不如维持简洁，session模式就足以覆盖project模式了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

看了vfox的源码，就是不管三七二十一，上来就创建一个新的shell进程，把要切换的版本路径添加到新的shell进程作为环境变量。这样做的一个坏处就是，如果你不断切换，最终shell进程会一层套一层，光浪费系统资源，啥也没做。
vmr的设计不是这样的，默认不创建新的shell，也不希望出现一层套一层的shell进程，这对有洁癖的人来说有点难受。而且，你要监控current working dir(cwd)的变化，势必要监控用户每次在终端中的输入，然后触发获取cwd与已缓存的各种目录做对比的操作，从而决定是否再使用另外版本的路径作为环境变量开启一个新的shell进程，这实际上也或多或少影响着用户在终端的输入回显速度，虽然可能大多数时候体验不那么明显。
基于这些考虑，不建议这样做。但是我们可以考虑怎么针对项目需要，在减少输入的情况下，快速的使用session模式激活某个版本。例如，可以记住某个本地文件夹曾经在session模式使用过的版本，下载在该文件夹下，就无需输入sdk@版本号，直接vmr use -s即可。
这样，既可以减少冗长的输入。也不至于让shell进程一层层嵌套。

**Comment by eryajf** [comment]
这里使用这种思路是否可行呢： https://github.com/nvm-sh/nvm#nvmrc

**Comment by moqsien** [comment]
> https://github.com/nvm-sh/nvm#nvmrc

晚点看一下可行性。

**Comment by eryajf** [comment]
我也有类似的场景，晚点我验证下看看

**Comment by moqsien** [comment]
> 我也有类似的场景，晚点我验证下看看

 可以的。

我觉得，最简单，就是在项目中生成一个.vmr.lock文件，用于持久化use命令的版本信息，这样下次不需要输入版本了，自动读取这个文件就行了。当然，可以搞一个遍历目录的寻找.vmr.lock文件的功能，方便在整个项目的任何文件夹中都可以找到这个.lock文件。

**Comment by eryajf** [comment]
> > 我也有类似的场景，晚点我验证下看看
> 
> 可以的。
> 
> 我觉得，最简单，就是在项目中生成一个.vmr.lock文件，用于持久化use命令的版本信息，这样下次不需要输入版本了，自动读取这个文件就行了。当然，可以搞一个遍历目录的寻找.vmr.lock文件的功能，方便在整个项目的任何文件夹中都可以找到这个.lock文件。

但这里还存在一个问题，通常这种切换应该是一个临时性的，而不应该全局生效，是不是现在执行了 vmr use 之后就全局生效了

**Comment by moqsien** [comment]
> > > 我也有类似的场景，晚点我验证下看看
> > 
> > 
> > 可以的。
> > 我觉得，最简单，就是在项目中生成一个.vmr.lock文件，用于持久化use命令的版本信息，这样下次不需要输入版本了，自动读取这个文件就行了。当然，可以搞一个遍历目录的寻找.vmr.lock文件的功能，方便在整个项目的任何文件夹中都可以找到这个.lock文件。
> 
> 但这里还存在一个问题，通常这种切换应该是一个临时性的，而不应该全局生效，是不是现在执行了 vmr use 之后就全局生效了

默认使用session模式读取.vmr.lock文件就可以了。

**Comment by moqsien** [comment]
我已经实现该功能，晚一点会和其他几个功能一起发布。

支持.vmr.lock文件锁定某个项目的sdk版本。锁定之后，在该项目内的任何目录下，只需要使用**vmr u**命令，即可一键切换到锁定版本的session模式，使用**exit**命令退出session后，全局版本不受影响。

**Comment by eryajf** [comment]
> 我已经实现该功能，晚一点会和其他几个功能一起发布。
> 
> 支持.vmr.lock文件锁定某个项目的sdk版本。锁定之后，在该项目内的任何目录下，只需要使用**vmr u**命令，即可一键切换到锁定版本的session模式，使用**exit**命令退出session后，全局版本不受影响。

优秀。
这里是不是进入该项目之后，还是需要执行一下 `vmr u` 才能切换，有没有可能不用执行就自动切换呢，我看nvm好像是在.zsh里加了一段脚本，没仔细看他的实现。

**Comment by moqsien** [comment]
> > 我已经实现该功能，晚一点会和其他几个功能一起发布。
> > 支持.vmr.lock文件锁定某个项目的sdk版本。锁定之后，在该项目内的任何目录下，只需要使用**vmr u**命令，即可一键切换到锁定版本的session模式，使用**exit**命令退出session后，全局版本不受影响。
> 
> 优秀。 这里是不是进入该项目之后，还是需要执行一下 `vmr u` 才能切换，有没有可能不用执行就自动切换呢，我看nvm好像是在.zsh里加了一段脚本，没仔细看他的实现。

那还是得监听用户输入吧，感觉跟vfox上来就开一个新shell的操作没啥两样啊。

**Comment by eryajf** [comment]
> > > 我已经实现该功能，晚一点会和其他几个功能一起发布。
> > > 支持.vmr.lock文件锁定某个项目的sdk版本。锁定之后，在该项目内的任何目录下，只需要使用**vmr u**命令，即可一键切换到锁定版本的session模式，使用**exit**命令退出session后，全局版本不受影响。
> > 
> > 
> > 优秀。 这里是不是进入该项目之后，还是需要执行一下 `vmr u` 才能切换，有没有可能不用执行就自动切换呢，我看nvm好像是在.zsh里加了一段脚本，没仔细看他的实现。
> 
> 那还是得监听用户输入吧，感觉跟vfox上来就开一个新shell的操作没啥两样啊。

他这里好像介绍了三种自动切的方案：https://github.com/nvm-sh/nvm#deeper-shell-integration  应该是zsh里边有能集成的hook，所以在切换目录的时候，可插入对应的命令。

**Comment by moqsien** [comment]
> > > > 我已经实现该功能，晚一点会和其他几个功能一起发布。
> > > > 支持.vmr.lock文件锁定某个项目的sdk版本。锁定之后，在该项目内的任何目录下，只需要使用**vmr u**命令，即可一键切换到锁定版本的session模式，使用**exit**命令退出session后，全局版本不受影响。
> > > 
> > > 
> > > 优秀。 这里是不是进入该项目之后，还是需要执行一下 `vmr u` 才能切换，有没有可能不用执行就自动切换呢，我看nvm好像是在.zsh里加了一段脚本，没仔细看他的实现。
> > 
> > 
> > 那还是得监听用户输入吧，感觉跟vfox上来就开一个新shell的操作没啥两样啊。
> 
> 他这里好像介绍了三种自动切的方案：https://github.com/nvm-sh/nvm#deeper-shell-integration 应该是zsh里边有能集成的hook，所以在切换目录的时候，可插入对应的命令。

已实现。

**vmr use -l sdk-name@version**命令可以在项目目录中锁定版本。
vmr在安装时，会注册一个**cdr**命令，和系统**cd**命令功能类似，只是增加了检查是否有锁定的sdk版本的功能，如果发现锁定版本，立即用session模式切换至锁定版本。退出终端session之后，锁定版本失效。

之所以使用**cdr**作为命令名称，是因为windows下别名无法覆盖powershell自带的命令。为保证统一，所有平台都注册为**cdr**，类unix系统用户如果习惯使用cd，可以手动把cdr设置别名为cd。

**Comment by eryajf** [comment]
太强了，我晚点准备写篇vmr的介绍文章，发布到 https://wiki.eryajf.net/
