### ISSUE TITLE
支持多版本glibc的管理？

### ISSUE THREAD

**Issue by janson653** [gvcgo/version-manager#140]
## Description

1. 能否支持多版本glibc，我的电脑目前是通过conda设置环境，然后指定环境变量LD_LIBRARY_PATH，让程序使用不同glibc

**Comment by moqsien** [comment]
vmr支持通过Conda一键安装未被vmr支持但是被Conda支持的SDK，但是需要自己手动配置环境变量。vmr的相关命令要比Conda简洁得多。

详见文档：https://vdocs.vmr.us.kg/zh-cn/guides/conda/

**Comment by moqsien** [comment]
![vmr_glibc](https://github.com/user-attachments/assets/1a6ea922-f25e-4a2e-a233-6b89e54b2646)

如上图所示，你可以自行通过vmr search -c xxx搜索Conda支持的SDK的版本列表。
然后通过vmr use -c xxx@version来安装对应的版本。
然后在~/.vmr/versions/xxx/xxx找到xxx的当前使用版本，将~/.vmr/versions/xxx/xxx/下面的任何目录加入PATH环境变量，下次使用vmr use -c xxx@version切换版本的时候就不需要添加PATH环境变量了。
