### ISSUE TITLE
卸载

### ISSUE THREAD

**Issue by Spritualkb** [gvcgo/version-manager#17]
希望尽快出一个一键卸载功能

**Comment by Spritualkb** [comment]
还有重装功能

**Comment by moqsien** [comment]
> 还有重装功能

更新方法和安装方法是一样的命令。

**Comment by Spritualkb** [comment]
作者写得很好，加油，对了最好可以相关配置数据一键导出和导入，感觉更加好

**Comment by fantasy-s** [comment]
vscode会安装在默认路径，没办法进行版本管理，另外建议自动添加VSCODE_EXTENSIONS环境变量把扩展转到其它盘

**Comment by moqsien** [comment]
> vscode会安装在默认路径，没办法进行版本管理，另外建议自动添加VSCODE_EXTENSIONS环境变量把扩展转到其它盘

vscode只支持最新的版本。一般来说，vscode都是使用最新版，需要版本管理的情况不多见。
安装在默认目录，是为了flutter doctor可以识别到，否则flutter doctor就识别不到了。

**Comment by moqsien** [comment]
> 作者写得很好，加油，对了最好可以相关配置数据一键导出和导入，感觉更加好

没懂什么意思。
