### ISSUE TITLE
vmr操作太过繁琐

### ISSUE THREAD

**Issue by Ive4** [gvcgo/version-manager#20]
建议使用list之后然后直接回车可以直接执行search操作，然后在search之后执行回车可以直接执行install操作。

**Comment by moqsien** [comment]
之前有同学提议过。

主要考虑到以下两点：
1、很多时候，我们只想看看有哪些版本，并不想安装。这样回车立即搜索/安装，容易造成很多误触。
2、在很多情况下，我们不是使用简单的use命令来安装或者切换sdk版本，还希望加其他参数，例如-l, -s, -c, -t等。

所以，按下回车之后，会把生成的下一步命令放入剪贴板，这样的话，你在粘贴进行下一步之前，可以编辑相关命令，从而达到你想要的效果。如果你不想进行下一步，那么就不用管了，这样也没有误触的情况。

因此，现在仅仅是多了一个ctrl+v或者cmd+v， 几乎没有影响多少效率。
