### ISSUE TITLE
支持 d语言编译器dmd版本管理

### ISSUE THREAD

**Issue by electricface** [gvcgo/version-manager#22]
可以下载安装D语言编译器 dmd 
已有项目 [jacob-carlborg/dvm: A tool to install and manage D compilers](https://github.com/jacob-carlborg/dvm) 可以参考

dmd下载地址：https://downloads.dlang.org/
命令有：ddemangle  dmd  dub  dustmite  rdmd

**Comment by moqsien** [comment]
> 可以下载安装D语言编译器 dmd 已有项目 [jacob-carlborg/dvm: A tool to install and manage D compilers](https://github.com/jacob-carlborg/dvm) 可以参考
> 
> dmd下载地址：https://downloads.dlang.org/ 命令有：ddemangle dmd dub dustmite rdmd

看了一下，可以列入计划。

**Comment by electricface** [comment]
D语言是个不错的语言

**Comment by moqsien** [comment]
> D语言是个不错的语言

预计五一期间能支持上Dlang。

**Comment by moqsien** [comment]
> D语言是个不错的语言

v0.1.8已经支持Dlang和Dlang的LSP serve-d。
