### ISSUE TITLE
python安装源中科大不能访问

### ISSUE THREAD

**Issue by mvpbang** [gvcgo/version-manager#23]
## 官方说明
<img width="638" alt="image" src="https://github.com/gvcgo/version-manager/assets/22229359/54cb801f-8adf-49ab-a4d1-b5f63da2c8fd">

- https://mirrors.ustc.edu.cn/help/anaconda.html

## 详见安装错误
<img width="807" alt="image" src="https://github.com/gvcgo/version-manager/assets/22229359/b32224bd-da40-4480-b0e8-b3ce43c08acc">

<img width="1205" alt="image" src="https://github.com/gvcgo/version-manager/assets/22229359/ff80faf8-ce24-43d2-be19-86bcd1844f0e">

**Comment by moqsien** [comment]
OK，感谢反馈。

后面会换成清华源。

**Comment by moqsien** [comment]
v0.1.8已修复，更换为清华源。
