### ISSUE TITLE
local查看python提示没安装

### ISSUE THREAD

**Issue by mvpbang** [gvcgo/version-manager#24]
# python查不到
<img width="832" alt="image" src="https://github.com/gvcgo/version-manager/assets/22229359/8ed91295-043b-44ff-8c68-dcfb67cf97c3">

# go的可以查到
<img width="1149" alt="image" src="https://github.com/gvcgo/version-manager/assets/22229359/e56f865e-f696-407a-bf60-83718d209712">

**Comment by moqsien** [comment]
你都没安装python，当然显示没有任何版本了。

vmr local sdk-name显示的是本地已安装的版本。

vmr list 显示的是vmr支持的sdk

vmr search sdk-name显示的是当前系统能够安装哪些版本

vmr use sdk-name@version是安装/切换到指定版本

**Comment by mvpbang** [comment]
> 你都没通过vmr安装python，当然显示没有任何版本了。
> 
> vmr local sdk-name显示的是本地已安装的版本。
> 
> vmr list 显示的是vmr支持的sdk
> 
> vmr search sdk-name显示的是当前系统能够安装哪些版本
> 
> vmr use sdk-name@version是安装/切换到指定版本

我在看下当初安装命令，第一次安装使用vmr use -s  python@3.8.10，去掉s在local就可以查到了

**Comment by moqsien** [comment]
> > 你都没通过vmr安装python，当然显示没有任何版本了。
> > vmr local sdk-name显示的是本地已安装的版本。
> > vmr list 显示的是vmr支持的sdk
> > vmr search sdk-name显示的是当前系统能够安装哪些版本
> > vmr use sdk-name@version是安装/切换到指定版本
> 
> 我在看下当初安装命令，第一次安装使用vmr use -s python@3.8.10，去掉s在local就可以查到了

我用vmr use -s python@3.12.3试了一下，无法复现你遇到的问题。
