### ISSUE TITLE
cdhook:2: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by mvpbang** [gvcgo/version-manager#25]
# macOS上提示
cdhook:2: maximum nested function level reached; increase FUNCNEST?

mvpbang@mvpbang ~ % cd zone 
cdhook:2: maximum nested function level reached; increase FUNCNEST?

<img width="1054" alt="image" src="https://github.com/gvcgo/version-manager/assets/22229359/d8f8a46d-7e7b-4c50-b260-8b38054e60d5">

# 疑惑
为啥 ~/.vm/vm_env.sh cdhook函数写两个，看着功能都是一样的

**Comment by moqsien** [comment]
把第二个cdhook() {} 函数删掉, 第二个alias cdr='cdhook'也可以删掉。

这是新版的hook没有覆盖旧版的hook造成的。之前觉得两个版本间隔时间很短，用的人应该不多，所以没做覆盖。后面改一下。

**Comment by mvpbang** [comment]
> 把第二个cdhook() {} 函数删掉, 第二个alias cdr='cdhook'也可以删掉。
> 
> 这是新版的hook没有覆盖旧版的hook造成的。之前觉得两个版本间隔时间很短，用的人应该不多，所以没做覆盖。后面改一下。

安装你说的，我在改了改就可以了。
<img width="1099" alt="image" src="https://github.com/gvcgo/version-manager/assets/22229359/3008db05-da29-44e1-97ac-e2e3529a83ff">

**Comment by moqsien** [comment]
已修复。
