### ISSUE TITLE
mvn命令无效

### ISSUE THREAD

**Issue by fantasy-s** [gvcgo/version-manager#27]
mvn命令无效，提示选择应用以打开mvn
![微信截图_20240503101805](https://github.com/gvcgo/version-manager/assets/110462544/cf384890-aad1-453f-8634-9c55f6529d36)

**Comment by moqsien** [comment]
大概知道问题了，晚一点修复。

**Comment by moqsien** [comment]
> mvn命令无效，提示选择应用以打开mvn ![微信截图_20240503101805](https://private-user-images.githubusercontent.com/110462544/327631695-cf384890-aad1-453f-8634-9c55f6529d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MDkyMjAsIm5iZiI6MTcxNDcwODkyMCwicGF0aCI6Ii8xMTA0NjI1NDQvMzI3NjMxNjk1LWNmMzg0ODkwLWFhZDEtNDUzZi04NjM0LTljNTVmNjUyOWQzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNDAyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjFkZjg1OWI1MjA2ODgyNzgyODUxMGVhZjA4NDMxYWUxZTZjMjBkMmZmYWViNmY0NmQ3MzVkMDQxMjBjNzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I7fGrrCclcJqQJJsRY-BmQXt6bGs4hOdYic3EKswwYs)

已修复。
使用**vmr-update**更新vmr，重新安装maven即可。
