### ISSUE TITLE
有关window创建软链接权限问题，有不用管理员权限的方案。

### ISSUE THREAD

**Issue by jan-bar** [gvcgo/version-manager#3]
我在别的项目解决了这个问题。

问题讨论：https://github.com/voidint/g/issues/51

参考代码：https://github.com/voidint/g/blob/67e947916569ea0c0a1ad467be0138fc422a17e9/cli/install.go#L162

**Comment by moqsien** [comment]
> 我在别的项目解决了这个问题。
> 
> 问题讨论：[voidint/g#51](https://github.com/voidint/g/issues/51)
> 
> 参考代码：https://github.com/voidint/g/blob/67e947916569ea0c0a1ad467be0138fc422a17e9/cli/install.go#L162

我记得这个mlink对于可执行文件的软连接，好像无法执行。你试过可以的吗？

**Comment by jan-bar** [comment]
> > 我在别的项目解决了这个问题。
> > 问题讨论：[voidint/g#51](https://github.com/voidint/g/issues/51)
> > 参考代码：https://github.com/voidint/g/blob/67e947916569ea0c0a1ad467be0138fc422a17e9/cli/install.go#L162
> 
> 我记得这个mlink对于可执行文件的软连接，好像无法执行。你试过可以的吗？

不都是对目录创建软连接么？我貌似没有在windows系统对可执行文件创建链接。一般都是对目录创建链接，把目录加入PATH环境变量。可执行文件创建链接执行会有问题，很多程序会相对可执行文件路径做一些操作，如果非要在别的目录执行另一个目录的可执行文件，我一般会写个bat脚本。

fnm也是创建目录软连接，不过是rust语言。貌似go语言在windows创建链接有些问题，标准库源码好像也有说明。

**Comment by moqsien** [comment]
对于很简单的一个执行文件，为了保持path变量整洁。vm都是创建一个连接到$HOME/.vm/bin 目录下，这样只需要添加这个bin目录即可。否则，PATH变量会随着安装sdk越多变得越杂。
vm在windows下会尝试创建软连接，不成功的话，会创建硬连接。一般来说，win10创建硬连接是可以不需要管理员权限的。win11则需要打开开发者模式。win11打开开发者模式后，软连接也能创建成功。

**Comment by moqsien** [comment]
如果有些windows系统下，确实需要管理员权限才能创建软/硬连接。可以考虑使用vm安装gsudo，gsudo是一个windows下的提权工具，类似于linux和mac下面的sudo，使用**gsudo vm use xxx@xxx**，即可方便地实现安装。

**Comment by jan-bar** [comment]
有方案就行。我个人喜欢 软连接目录，其次就是vfox那种设置PATH(实际上切换语言环境不止设置PATH)，我也推荐vfox作者设置软连接，但他说服我设置PATH的好处。

不过话说回来，我还是喜欢开箱即用的方案额。

**Comment by moqsien** [comment]
> 有方案就行。我个人喜欢 软连接目录，其次就是vfox那种设置PATH(实际上切换语言环境不止设置PATH)，我也推荐vfox作者设置软连接，但他说服我设置PATH的好处。
> 
> 不过话说回来，我还是喜欢开箱即用的方案额。

vfox噱头比较多，实用的少。所谓的session，根本没啥用，难不成指望所有任务在当前命令行窗口去完成？或许对脚本语言还有点用，就像python的虚拟环境一样，编译型还是算了吧。session功能聊胜于无吧，可以当个卖点吹一吹。

至于可扩展性，仿照neovim引入运行时来解决，这就有点低估了各种官网，各种资源，压缩包，安装文件的不够统一的程度了。完全有点脱裤子放屁，带来复杂度不说，也没有解决什么实质性的问题，更导致各种不稳定，影响使用体验。当然，这是个可以吹的卖点，听起来高大上一点。之前gvc考虑过引入lua运行时的方式，但是仔细思考了一下，给否了。

最稳的做法，还是把爬取各种资源的这一部分独立，让所有资源数据格式统一集中到某个仓库。这样用户的体验才最好。

**Comment by jan-bar** [comment]
session这点我不同意，fnm也是基于session的。可以做到不同终端用各不相同的版本，对我很有用。比如我的go代码的go.mod是go 1.18，但我日常用go1.22。我希望我的代码也能用go 1.18编译，避免用到了非go 1.18的功能。这时候我想新开一个终端用非当前常用版本去编译项目。

有不同想法很正常，就让时间来检验成果吧。

**Comment by moqsien** [comment]
> fnm

不是争辩session这个问题啊。单纯解释一下。
就是我开个终端，切换到某个版本，用完之后，切换回去。大概也就多一条切换回去的命令。
甚至这条切换回去的命令，可以有快捷方式。

我当时也对vfox的session这个功能有点好奇，看了一下源码，感觉有点吹了，不过没去尝试具体功能。看代码，不像是什么隔离的环境，要实现，也不复杂，记住之前的，用完切回去。

搞不懂，反正我没有session这样的概念需求。倒是可以做一个切换到上一个使用版本的快捷命令，这样少了查看当前版本的操作。
