### ISSUE TITLE
[vmr search jdk]列表中未找到Java1.8

### ISSUE THREAD

**Issue by ikeukenhof** [gvcgo/version-manager#40]
1. 使用`vmr search jdk`后，通过"`↑/k`"，"`↓/j`"并未在列表中找到**Java1.8**
2. 之前有通过`brew`安装过`gradle6.x`（在`.zprofile`文件中`export PATH="/opt/homebrew/Cellar/gradle`）, 现在通过`vmr`安装`gradle8.x`，请问该如何在这两个版本之间做切换呢（是通过`env`吗）？没太明白`vmr env `的用法，能否给个具体例子。

谢谢🙏

**Comment by moqsien** [comment]
![jdk](https://github.com/gvcgo/version-manager/assets/34511192/4b9dc1c0-144c-4f8c-99bc-999332247dfa)

**Comment by ikeukenhof** [comment]
> ![jdk](https://private-user-images.githubusercontent.com/34511192/330800377-4b9dc1c0-144c-4f8c-99bc-999332247dfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzU5MTIsIm5iZiI6MTcxNTc3NTYxMiwicGF0aCI6Ii8zNDUxMTE5Mi8zMzA4MDAzNzctNGI5ZGMxYzAtMTQ0Yy00ZjhjLTk5YmMtOTk5MzMyMjQ3ZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyMjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZGI4ZTgzNTM2MGUxMDk1NzlmY2IyNWNmOGNhMjY0Zjc4NDdhOWE3NzZhYzdjYzE0MjBjNzg0NGFlNmE3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gI3ELc3I-sbQeX3D-wDfFIwCP3YfdPpF9umeQiGmvp4)
> 
> 8u开头的都是1.8
> 
> vmr只能支持通过vmr安装的SDK之间切换。

<img width="461" alt="image" src="https://github.com/gvcgo/version-manager/assets/41727828/6a18b178-2a25-46a8-b781-cc6a8b6b5dba">
<img width="473" alt="image" src="https://github.com/gvcgo/version-manager/assets/41727828/182faf9c-afde-4d92-be1e-d9703930ed96">
好奇怪，我向下翻，只到“18_36”，再往下就没了

**Comment by moqsien** [comment]
设置反向代理：
[文档](https://gvcgo.github.io/vmrdocs/#/zh-cn/usage?id=%e8%ae%be%e7%bd%ae%e4%bb%a3%e7%90%86)

需要访问github，如果没设置代理，有可能出现请求内容不完整吧。

**Comment by ikeukenhof** [comment]
> 设置反向代理： [文档](https://gvcgo.github.io/vmrdocs/#/zh-cn/usage?id=%e8%ae%be%e7%bd%ae%e4%bb%a3%e7%90%86)
> 
> 需要访问github，如果没设置代理，有可能出现请求内容不完整吧。

设置反向代理后，重新打开终端，`vmr search jdk`仍然没有java1.8的版本（仍然只是到`18_36`），并且尝试通过`vmr use "jdk@8u352-b08"`安装，结果😭
<img width="408" alt="image" src="https://github.com/gvcgo/version-manager/assets/41727828/cad597c3-4fd5-4cf0-a283-a75d0a923dd9">

**Comment by moqsien** [comment]
> > 设置反向代理： [文档](https://gvcgo.github.io/vmrdocs/#/zh-cn/usage?id=%e8%ae%be%e7%bd%ae%e4%bb%a3%e7%90%86)
> > 需要访问github，如果没设置代理，有可能出现请求内容不完整吧。
> 
> 设置反向代理后，重新打开终端，`vmr search jdk`仍然没有java1.8的版本（仍然只是到`18_36`），并且尝试通过`vmr use "jdk@8u352-b08"`安装，结果😭 <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/41727828/330806627-cad597c3-4fd5-4cf0-a283-a75d0a923dd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzcyNzksIm5iZiI6MTcxNTc3Njk3OSwicGF0aCI6Ii80MTcyNzgyOC8zMzA4MDY2MjctY2FkNTk3YzMtNGZkNS00Y2YwLWEyODMtYTc1ZDBhOTIzZGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEyNDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMzVmMmY1MDJkYTlhMTJkN2MwOTBhZjQxOWU2MmIxODQ1OTg1MGE1YjA1Mjg0OTQwNmFhMmM2ODQwMzk5YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YbCxkCXYD4zNUgazrYCKHEl3wZ0CVQteibhXA-M6Q2U">

什么系统？

**Comment by moqsien** [comment]
如果你是苹果M芯片的，那估计就是没有。

**Comment by moqsien** [comment]
> > 如果你是苹果M芯片的，那估计就是没有。
> > vmr使用的是adoptium的jdk。
> > https://github.com/adoptium/temurin8-binaries/releases
> > 可以对照，是否支持你的设备。
> > 如果是这样的话，vmr后面可以考虑换个发型版。
> 
> 不好意思，未事先声明使用的设备。 我是用确实是苹果m芯片的设备，感谢您的解答，谢谢🙏

没事。发现了一个问题也可以。这种的话，后面换个发行版就好了。
