### ISSUE TITLE
国内无法搜索到 v 语言

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#42]
(base) root@Jengro:/# vmr search v
Get "https://raw.githubusercontent.com/gvcgo/resources/main/v.version.json": proxyconnect tcp: dial tcp 192.168.3.2:59511: i/o timeout
  ERROR   Download version list failed: 400
 WARNING  No versions found!

**Comment by Avey777** [comment]
(base) root@Jengro:~# vmr search v
Get "https://raw.githubusercontent.com/gvcgo/resources/main/v.version.json": dial tcp 0.0.0.0:443: connect: connection refused
  ERROR   Download version list failed: 400
 WARNING  No versions found!
(base) root@Jengro:~#

**Comment by Avey777** [comment]
希望 搜索这些软件的时候可以不适用代理，代理用起来很繁琐。 期待有开箱即用的方案

**Comment by moqsien** [comment]
> 希望 搜索这些软件的时候可以不适用代理，代理用起来很繁琐。 期待有开箱即用的方案

https://gvcgo.github.io/vmrdocs/#/zh-cn/usage?id=%e8%ae%be%e7%bd%ae%e4%bb%a3%e7%90%86
