### ISSUE TITLE
windows 安装go之后无法go version，不会配置go的环境变量吗？

### ISSUE THREAD

**Issue by tr1gv0n** [gvcgo/version-manager#45]
![Snipaste_2024-05-22_15-26-01](https://github.com/gvcgo/version-manager/assets/30565986/436e679e-2723-4e7a-9295-fc879fe70e5e)

**Comment by moqsien** [comment]
解决方法：
- 关闭当前powershell，重新打开一个。
或者
- source命令。（**vmr 给windows用户定义了source命令，用于刷新环境变量**）

**Comment by tr1gv0n** [comment]
> 解决方法：
> 
> * 关闭当前powershell，重新打开一个。
>   或者
> * source命令。（**vmr 给windows用户定义了source命令，用于刷新环境变量**）

![Snipaste_2024-05-22_16-24-14](https://github.com/gvcgo/version-manager/assets/30565986/906aa70d-f499-4e2f-b22b-d4da58182173)
如图，新打开powershell，不生效。您说的source命令应该怎么使用，是做为vmr命令的子参数？

**Comment by tr1gv0n** [comment]
可以了老师，鼓捣好了
