### ISSUE TITLE
vmr 0.6.1 预发布版，首次使用提示“no sdk found!”

### ISSUE THREAD

**Issue by wgjas2** [gvcgo/version-manager#49]
首次运行vmr，如果连不上代理，sdk_list内容为空，则提示代理连接失败的信息以及“no sdk found!”，但是后续重新执行一直只提示“no sdk found!”，无法重新获取sdk列表，手动删除sdk_list后才能重新获取

**Comment by moqsien** [comment]
> 首次运行vmr，如果连不上代理，sdk_list内容为空，则提示代理连接失败的信息以及“no sdk found!”，但是后续重新执行一直只提示“no sdk found!”，无法重新获取sdk列表，手动删除sdk_list后才能重新获取

已修。
