### ISSUE TITLE
[bug] install 404

### ISSUE THREAD

**Issue by cffycls** [gvcgo/version-manager#5]
PS D:\work> powershell -nop -c "iex(New-Object Net.WebClient).DownloadString('https://gvc.1710717.xyz/proxy/https://raw.githubusercontent.com/gvcgo/version-manager/main/scripts/install.ps1')"

Downloading files...
Invoke-RestMethod : 远程服务器返回错误: (404) 未找到。
所在位置 行:40 字符: 1
+ Invoke-RestMethod -Uri $url -OutFile $filename
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

--------------------------------------------------
可以在浏览器上打开代理站。多次重试了，网络无问题，查看脚本下载地址是：
https://gvc.1710717.xyz/proxy/https://github.com/gvcgo/version-manager/releases/download/v0.1.3/vm_windows-.zip

vm_windows-.zip 应该是 vm_windows-amd64.zip
```
PS D:\work> systeminfo

主机名:           WIN-N9RB7945R37
...
系统型号:         82R4
系统类型:         x64-based PC
...
```
中文未匹配，或使用默认值

**Comment by moqsien** [comment]
OK，在我的windows虚拟机测试正常。没想到会在其他机器匹配不了。
鉴于windows基本上都是x86-64，那就改为默认值好了。

感谢提出。
