### ISSUE TITLE
vmr-update 更新会丢失 vmr 可执行文件

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#50]
os：debian12 
vmr：v0.6.1
使用vmr-update更新后，vmr可执行文件丢失。
再次更新依旧不会有vmr可执行文件，在不删除  .vm 文件的前提下使用安装命令依旧不行

**Comment by moqsien** [comment]
> os：debian12 vmr：v0.6.1 使用vmr-update更新后，vmr可执行文件丢失。 再次更新依旧不会有vmr可执行文件，在不删除 .vm 文件的前提下使用安装命令依旧不行

已修复。复制安装命令重新安装即可。

**Comment by Avey777** [comment]
> > os：debian12 vmr：v0.6.1 使用vmr-update更新后，vmr可执行文件丢失。 再次更新依旧不会有vmr可执行文件，在不删除 .vm 文件的前提下使用安装命令依旧不行
> 
> 已修复。复制安装命令重新安装即可。

重新安装确实可以了，但是更新还是不可以。 更新会删除vmr
