### ISSUE TITLE
支持 Clojure

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#51]
https://www.clojure.org/

clojure 是metabase的开发语言，做二次开发需要配置。 希望可以支持这个语言的版本管理

**Comment by moqsien** [comment]
cloujure太小众，我不熟悉。但看官网，发布的是jar包，是通过maven安装的。
不确定怎么实现。

有感兴趣的，可以提供方案，贡献代码。

**Comment by moqsien** [comment]
> 我猜楼主说的是 Clojure CLI。
> 
> [Release](https://github.com/clojure/brew-install/releases/tag/1.11.3.1463) 页面有install脚本，里面有安装流程；jar包直接从里面拖下来就了。

这个release里面就是clojure的安装包吗？
如果是这样，那支持起来很简单。

**Comment by Avey777** [comment]
> > 我猜楼主说的是 Clojure CLI。
> > [Release](https://github.com/clojure/brew-install/releases/tag/1.11.3.1463) 页面有install脚本，里面有安装流程；jar包直接从里面拖下来就了。
> 
> 这个release里面就是clojure的安装包吗？ 如果是这样，那支持起来很简单。

是的

**Comment by moqsien** [comment]
> > > 我猜楼主说的是 Clojure CLI。
> > > [Release](https://github.com/clojure/brew-install/releases/tag/1.11.3.1463) 页面有install脚本，里面有安装流程；jar包直接从里面拖下来就了。
> > 
> > 
> > 这个release里面就是clojure的安装包吗？ 如果是这样，那支持起来很简单。
> 
> 是的

v0.6.2已支持。
