### ISSUE TITLE
vmr-update 更新会丢失 vmr可执行文件

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#52]
使用  vmr-update 更新丢失vmr可执行文件的问题并没有被修复从 0.6.1到0.6.2 都是

**Comment by Avey777** [comment]
![image](https://github.com/gvcgo/version-manager/assets/35259040/1e703111-2587-4dea-857f-119acaabd326)

**Comment by Avey777** [comment]
![image](https://github.com/gvcgo/version-manager/assets/35259040/7d8a27ff-9586-4390-b639-2f2d8c779205)

**Comment by moqsien** [comment]
删除.vm以及.vmr/vmr-update。然后重装vmr，再测试vmr-update。不要混用。

**Comment by Avey777** [comment]
![image](https://github.com/gvcgo/version-manager/assets/35259040/d01f06e2-768c-461b-8eab-c6bbbd9eea8b)
删除两个文件夹，全新安装就这样了。 这样更新 把我之前配好的环境都搞乱了。

**Comment by Avey777** [comment]
![image](https://github.com/gvcgo/version-manager/assets/35259040/b681bbf7-732c-4bb0-9cea-5a1a208fe090)

**Comment by moqsien** [comment]
> ![image](https://private-user-images.githubusercontent.com/35259040/336334601-d01f06e2-768c-461b-8eab-c6bbbd9eea8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODQxMDIsIm5iZiI6MTcxNzQ4MzgwMiwicGF0aCI6Ii8zNTI1OTA0MC8zMzYzMzQ2MDEtZDAxZjA2ZTItNzY4Yy00NjFiLThlYWItYzZiYmJkOWVlYThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2NTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNGJiMzdkNjU5Mjc1YjlmYzQwMGNlNGYxNDQ2MzNkMDc5MjJmNDBmYjYyZDllZTFmNzQ4ZmY4OTE4YTIyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d6W2FejuzeQA7J_P8-TqQDMgTeGamefJ_1XcMc1p0Bg) 删除两个文件夹，全新安装就这样了。 这样更新 把我之前配好的环境都搞乱了。

大哥，读一下文档呀： https://gvcgo.github.io/vdocs/#/zh-cn/usage

新版已经不需要命令了，直接**vmr**进入TUI界面，界面上各种快捷按键提示。

这样就不需要记那么多命令了， 按照提示一步步操作即可。这是之前很多同学期望的。

**Comment by Avey777** [comment]
建议 保留 search 和 local 功能，看每个人使用习惯

**Comment by moqsien** [comment]
习惯了就好了。
确实减少了很多输入，直观不用记命令，拿着就能上手， 甚至都不怎么需要文档。

**Comment by Avey777** [comment]
> 习惯了就好了。 确实减少了很多输入，直观不用记命令，拿着就能上手， 甚至都不怎么需要文档。
我之所以说是因为我使用1panel 面板， 它家的终端 按 j k 上下箭头选择 是不起作用的，我也不知道为什么？ 现在我要使用vmr 还要单独使用其他的终端才行

**Comment by Avey777** [comment]
> 习惯了就好了。 确实减少了很多输入，直观不用记命令，拿着就能上手， 甚至都不怎么需要文档。

你可以自己使用下 1Panel 面板吗？  j  k 和上下箭头不能选择，  我就用不了vmr 了

**Comment by Avey777** [comment]
支持就支持呗，干嘛直接去掉命令。
