### ISSUE TITLE
1Panel 等部分终端不能使用0.6.2 更新的命令方式

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#53]
由于0.6.2版本去掉了  search  local  install 等命令，导致1Panel等面板终端，无法使用vmr

具体原因： 在1panel 等面板中。按 j 、k 或者上下箭头 不能进行选择

**Comment by moqsien** [comment]
小众的，不用提。
这个估计一般都没法解决，只能你自己有环境，自己贡献代码。

**Comment by Avey777** [comment]
> 小众的，不用提。 这个估计一般都没法解决，只能你自己有环境，自己贡献代码了。

1panel 还小众？ 好吧 算我无知
