### ISSUE TITLE
0.6.2 使用vmr-update 更新，依旧会丢失 vmr 可执行文件

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#54]
![image](https://github.com/gvcgo/version-manager/assets/35259040/30ae437c-779b-4bca-bd2b-27f20403a194)

**Comment by Avey777** [comment]
![image](https://github.com/gvcgo/version-manager/assets/35259040/60de71a9-66e0-40f6-94cb-2e2b1d0e2c3f)
这个更方便辅助排查问题

**Comment by moqsien** [comment]
你看看vmr-update脚本就知道了。
更新不需要切换到.vmr目录，切换了，反而最后一起连安装的文件都清除了。
这是万万没想到啊。太难了。

**Comment by Avey777** [comment]
> 你看看vmr-update脚本就知道了。 更新不需要切换到.vmr目录，切换了，反而最后一起连安装的文件都清除了。 这是万万没想到啊。太难了。

理解了，我以为  vmr-update  不能外部使用
