### ISSUE TITLE
cd 命令与原来的行为不一致

### ISSUE THREAD

**Issue by snail2sky** [gvcgo/version-manager#56]
平时用命令 会直接 `cd` 来回到家目录，不带任何参数
但是最近发现直接 `cd` 没用了，不回家了，但是cd到别的目录是可以的
1. 查看cd命令是不是被篡改了, `which cd`  发现cd 是正确的, `alias cd` ，哎呦 果然被改了，但是还不知道是被哪个软件改的
2. 继续排查，是在哪个文件中被修改的，查看了 /etc/bashrc 和 ~/.bashrc ，发现都没有被篡改，继续排查 bash -x 以debug方式进入一个新的shell，然后果然发现了问题 
![image](https://github.com/gvcgo/version-manager/assets/49757958/6f562a05-dbf4-4daf-8891-66f38c9f2f91)
3. 进入这个文件查看 
![image](https://github.com/gvcgo/version-manager/assets/49757958/a50581a9-59c6-4f9c-9d33-5c33c3ec5c91)
4. 问题就比较清楚了，如果 $1 不是一个存在目录，那么就什么都不做，所以我直接`cd`，那根本就没有$1，肯定不存在，因此什么都不做~
5. 如何修改，这样改就好了 , `vim ~/.vm/vm_env.sh`
```bash
# cd hook start
cdalias=`alias|grep cdhook`
if [ -z "$cdalias" ]; then
	cdhook() {
		if [ $# -eq 0 ]; then
			\cd
		else
			\cd "$@" && vmr use -E
		fi
	}
	alias cd='cdhook'
fi
# cd hook end
```

**Comment by moqsien** [comment]
ok, 晚点修复，感谢反馈。

**Comment by moqsien** [comment]
已修复。

**Comment by snail2sky** [comment]
> 已修复。

大佬给力
