### ISSUE TITLE
切换到python环境的时候是否可以把scripts目录也加到环境变量

### ISSUE THREAD

**Issue by heheda123123** [gvcgo/version-manager#58]
如图，通过pip安装的程序，在scripts下。pip本身也要用python -m pip来执行
![image](https://github.com/gvcgo/version-manager/assets/97490782/01bd7ee2-dbba-4228-b13e-531e9d651d5b)

**Comment by moqsien** [comment]
哦，这个Scripts，应该只有windows下，才是把运行脚本放在里面。MacOS和Linux，都是直接放在bin下面，是吧？

**Comment by moqsien** [comment]
已修复，估计过一会就好了，版本安装仓库会自动更新，用户无需任何操作。
