### ISSUE TITLE
没有卸载命令

### ISSUE THREAD

**Issue by eryajf** [gvcgo/version-manager#59]
可能是我一开始安装了老版本，一路升级上来的原因。当前我的版本是：

```
$ vmr version
v0.1.8(4af72c3)
```

我单独执行vmr命令，不会进入到tui界面，所以打算卸载重新安装，此时执行：

```
$ vmr-uninstall
zsh: command not found: vmr-uninstall
```

这种情况下，如何完全卸载并重新安装呢。

**Comment by moqsien** [comment]
0.6.x在安装过程中，会自动检测并询问是否卸载0.1.x及其安装的SDK，同意才能继续安装0.6.x。

**Comment by eryajf** [comment]
恩恩，那文档那里可以补充下，在这个版本跨度时，单纯执行 vmr-update 并不会升级上来。

**Comment by eryajf** [comment]
卡在这里三分钟了，应该是有啥问题：

<img width="1330" alt="image" src="https://github.com/gvcgo/version-manager/assets/33259379/1b3ba7df-86e9-4211-8890-7d28663db559">

**Comment by eryajf** [comment]
不知道是不是这个原因：

```
$ ll .vm
.vm/   .vmr/
```

有两个目录存在的原因吗。我打算rm掉，然后重新安装试试。

**Comment by eryajf** [comment]
补充：手动删除之后，重新安装，还需要单独处理下 .zshrc 的环境变化，把老的 vm 的配置信息删掉，不然会找不到vmr命令。

**Comment by eryajf** [comment]
新版本use之后，貌似没有自动加载环境变量：

```
eryajf in ~/.vmr [9:44:23]
$ vmr
  INFO    node 16.20.2 is already installed.

eryajf in ~/.vmr [9:47:49]
$ node -v
zsh: command not found: node
```

我不记得老版本是否还需要手动加载一下。

**Comment by moqsien** [comment]
> 卡在这里三分钟了，应该是有啥问题：
> 
> <img alt="image" width="1330" src="https://private-user-images.githubusercontent.com/33259379/338792987-1b3ba7df-86e9-4211-8890-7d28663db559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTcxNTAsIm5iZiI6MTcxODE1Njg1MCwicGF0aCI6Ii8zMzI1OTM3OS8zMzg3OTI5ODctMWIzYmE3ZGYtODZlOS00MjExLTg4OTAtN2QyODY2M2RiNTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViN2JjZjMzYTA4NTE4NjE0ZTM3N2Q4YjdlOGRjMDFhNTg5ZDgxODVlOTM4ZGJiZjUzNzRkMDE1OTU0NDAwYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._XHsfVrHyaqLfNhLtBRS5EXioUqexTW4TXEUWNPjOss">

如果安装的SDK比较多，删除会比较慢。

**Comment by moqsien** [comment]
> 新版本use之后，貌似没有自动加载环境变量：
> 
> ```
> eryajf in ~/.vmr [9:44:23]
> $ vmr
>   INFO    node 16.20.2 is already installed.
> 
> eryajf in ~/.vmr [9:47:49]
> $ node -v
> zsh: command not found: node
> ```
> 
> 我不记得老版本是否还需要手动加载一下。

首次安装SDK会出现，source一下就好了。

**Comment by eryajf** [comment]
@moqsien node的版本只能搜索到v16，再往下的搜索不到：

<img width="341" alt="image" src="https://github.com/gvcgo/version-manager/assets/33259379/0890da3f-c37f-4147-9fb4-a65eb33e7f39">

**Comment by moqsien** [comment]
> @moqsien node的版本只能搜索到v16，再往下的搜索不到：
> 
> <img alt="image" width="341" src="https://private-user-images.githubusercontent.com/33259379/338797429-0890da3f-c37f-4147-9fb4-a65eb33e7f39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTkxMzQsIm5iZiI6MTcxODE1ODgzNCwicGF0aCI6Ii8zMzI1OTM3OS8zMzg3OTc0MjktMDg5MGRhM2YtYzM3Zi00MTQ3LTlmYjQtYTY1ZWIzM2U3ZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzRkYmNhZjY1ZDNmN2UzMGNlMmNjM2Y3NjBiYjFiNTVjOGEwZWVlZmE4MTJhNjIzYmRiMmM3Yjk2ODViNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sObWLKP0ihLkknJxFLqCGf4iZ4teMsVrC8RW4kyrPfU">

https://github.com/gvcgo/vsources/blob/main/node.version.json
https://nodejs.org/download/release/v14.1.0/

自行参考，是否自己的os-arch支持相关版本。

**Comment by eryajf** [comment]
现在0.6.x增加了这层校验吧，但之前0.1.x是可以安装，也能够正常使用。
那我再把版本降一下吧😂

**Comment by eryajf** [comment]
> > @moqsien node的版本只能搜索到v16，再往下的搜索不到：
> > <img alt="image" width="341" src="https://private-user-images.githubusercontent.com/33259379/338797429-0890da3f-c37f-4147-9fb4-a65eb33e7f39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTkxMzQsIm5iZiI6MTcxODE1ODgzNCwicGF0aCI6Ii8zMzI1OTM3OS8zMzg3OTc0MjktMDg5MGRhM2YtYzM3Zi00MTQ3LTlmYjQtYTY1ZWIzM2U3ZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzRkYmNhZjY1ZDNmN2UzMGNlMmNjM2Y3NjBiYjFiNTVjOGEwZWVlZmE4MTJhNjIzYmRiMmM3Yjk2ODViNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sObWLKP0ihLkknJxFLqCGf4iZ4teMsVrC8RW4kyrPfU">
> 
> [gvcgo/vsources@`main`/node.version.json](https://github.com/gvcgo/vsources/blob/main/node.version.json?rgh-link-date=2024-06-12T02%3A21%3A33Z) [nodejs.org/download/release/v14.1.0](https://nodejs.org/download/release/v14.1.0/)
> 
> 自行参考，是否自己的os-arch支持相关版本。

这里可能要考虑下，是否升级到 0.6.x 之后，就无法使用vmr管理node低于16的版本了。看了下nvm他通过源码编译安装的，这边我建议还是支持安装，毕竟是可用的，且用下来没什么问题的。但如果升级到0.6.x之后直接没有了，对于有此需求的人(不少老项目得用v14)，难道还要再安装nvm管理node么，这样岂不是与vmr理念相悖了。

**Comment by moqsien** [comment]
> > > @moqsien node的版本只能搜索到v16，再往下的搜索不到：
> > > <img alt="image" width="341" src="https://private-user-images.githubusercontent.com/33259379/338797429-0890da3f-c37f-4147-9fb4-a65eb33e7f39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTkxMzQsIm5iZiI6MTcxODE1ODgzNCwicGF0aCI6Ii8zMzI1OTM3OS8zMzg3OTc0MjktMDg5MGRhM2YtYzM3Zi00MTQ3LTlmYjQtYTY1ZWIzM2U3ZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzRkYmNhZjY1ZDNmN2UzMGNlMmNjM2Y3NjBiYjFiNTVjOGEwZWVlZmE4MTJhNjIzYmRiMmM3Yjk2ODViNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sObWLKP0ihLkknJxFLqCGf4iZ4teMsVrC8RW4kyrPfU">
> > 
> > 
> > [gvcgo/vsources@`main`/node.version.json](https://github.com/gvcgo/vsources/blob/main/node.version.json?rgh-link-date=2024-06-12T02%3A21%3A33Z) [nodejs.org/download/release/v14.1.0](https://nodejs.org/download/release/v14.1.0/)
> > 自行参考，是否自己的os-arch支持相关版本。
> 
> 这里可能要考虑下，是否升级到 0.6.x 之后，就无法使用vmr管理node低于16的版本了。看了下nvm他通过源码编译安装的，这边我建议还是支持安装，毕竟是可用的，且用下来没什么问题的。但如果升级到0.6.x之后直接没有了，对于有此需求的人(不少老项目得用v14)，难道还要再安装nvm管理node么，这样岂不是与vmr理念相悖了。

你是说，node官网的v14的darwin-x64版本，其实是可以给macos M芯片用的？

**Comment by eryajf** [comment]
> > > > @moqsien node的版本只能搜索到v16，再往下的搜索不到：
> > > > <img alt="image" width="341" src="https://private-user-images.githubusercontent.com/33259379/338797429-0890da3f-c37f-4147-9fb4-a65eb33e7f39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTkxMzQsIm5iZiI6MTcxODE1ODgzNCwicGF0aCI6Ii8zMzI1OTM3OS8zMzg3OTc0MjktMDg5MGRhM2YtYzM3Zi00MTQ3LTlmYjQtYTY1ZWIzM2U3ZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzRkYmNhZjY1ZDNmN2UzMGNlMmNjM2Y3NjBiYjFiNTVjOGEwZWVlZmE4MTJhNjIzYmRiMmM3Yjk2ODViNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sObWLKP0ihLkknJxFLqCGf4iZ4teMsVrC8RW4kyrPfU">
> > > 
> > > 
> > > [gvcgo/vsources@`main`/node.version.json](https://github.com/gvcgo/vsources/blob/main/node.version.json?rgh-link-date=2024-06-12T03%3A34%3A48Z) [nodejs.org/download/release/v14.1.0](https://nodejs.org/download/release/v14.1.0/)
> > > 自行参考，是否自己的os-arch支持相关版本。
> > 
> > 
> > 这里可能要考虑下，是否升级到 0.6.x 之后，就无法使用vmr管理node低于16的版本了。看了下nvm他通过源码编译安装的，这边我建议还是支持安装，毕竟是可用的，且用下来没什么问题的。但如果升级到0.6.x之后直接没有了，对于有此需求的人(不少老项目得用v14)，难道还要再安装nvm管理node么，这样岂不是与vmr理念相悖了。
> 
> 你是说，node官网的v14的darwin-x64版本，其实是可以给macos M芯片用的？

是的，我之前用的vmr-0.1.x的时候，就安装了nodejs-v14，然后本地开发前端项目是没问题的。

**Comment by moqsien** [comment]
> > > > > @moqsien node的版本只能搜索到v16，再往下的搜索不到：
> > > > > <img alt="image" width="341" src="https://private-user-images.githubusercontent.com/33259379/338797429-0890da3f-c37f-4147-9fb4-a65eb33e7f39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTkxMzQsIm5iZiI6MTcxODE1ODgzNCwicGF0aCI6Ii8zMzI1OTM3OS8zMzg3OTc0MjktMDg5MGRhM2YtYzM3Zi00MTQ3LTlmYjQtYTY1ZWIzM2U3ZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzRkYmNhZjY1ZDNmN2UzMGNlMmNjM2Y3NjBiYjFiNTVjOGEwZWVlZmE4MTJhNjIzYmRiMmM3Yjk2ODViNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sObWLKP0ihLkknJxFLqCGf4iZ4teMsVrC8RW4kyrPfU">
> > > > 
> > > > 
> > > > [gvcgo/vsources@`main`/node.version.json](https://github.com/gvcgo/vsources/blob/main/node.version.json?rgh-link-date=2024-06-12T03%3A34%3A48Z) [nodejs.org/download/release/v14.1.0](https://nodejs.org/download/release/v14.1.0/)
> > > > 自行参考，是否自己的os-arch支持相关版本。
> > > 
> > > 
> > > 这里可能要考虑下，是否升级到 0.6.x 之后，就无法使用vmr管理node低于16的版本了。看了下nvm他通过源码编译安装的，这边我建议还是支持安装，毕竟是可用的，且用下来没什么问题的。但如果升级到0.6.x之后直接没有了，对于有此需求的人(不少老项目得用v14)，难道还要再安装nvm管理node么，这样岂不是与vmr理念相悖了。
> > 
> > 
> > 你是说，node官网的v14的darwin-x64版本，其实是可以给macos M芯片用的？
> 
> 是的，我之前用的vmr-0.1.x的时候，就安装了nodejs-v14，然后本地开发前端项目是没问题的。

那应该是开了Rosetta兼容。

那可以考虑把node的低版本的darwin版本的arch设置为any，但是得用户自行使用Rosseta兼容。

**Comment by eryajf** [comment]
我这里切回0.1之后，显示是intel，但实际开发编译都能过去：

<img width="1370" alt="image" src="https://github.com/gvcgo/version-manager/assets/33259379/252e97e8-95e8-449f-b032-07ef521d412d">

我看了下item的终端没有开启rosetta。


> 那可以考虑把node的低版本的darwin版本的arch设置为any

期待这个调整。

**Comment by moqsien** [comment]
> 我这里切回0.1之后，显示是intel，但实际开发编译都能过去：
> 
> <img alt="image" width="1370" src="https://private-user-images.githubusercontent.com/33259379/338815892-252e97e8-95e8-449f-b032-07ef521d412d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzYwNDEsIm5iZiI6MTcxODE3NTc0MSwicGF0aCI6Ii8zMzI1OTM3OS8zMzg4MTU4OTItMjUyZTk3ZTgtOTVlOC00NDlmLWIwMzItMDdlZjUyMWQ0MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA3MDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYjNlYTZhNDI3YWMxZjQzNzI2YzBjOWIxZDc3N2NjNDJlNDVmZjQ5NWIzZDFmMTk2NzM2ODFiZDlmOTAzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pso4rMxGpbO8FLDewglYwNazHO-gEY09PACOuB1uZoU">
> 我看了下item的终端没有开启rosetta。
> 
> > 那可以考虑把node的低版本的darwin版本的arch设置为any
> 
> 期待这个调整。

应该可以了。

**Comment by eryajf** [comment]
OK，可以了👏
