### ISSUE TITLE
[warn] operate commands in win11

### ISSUE THREAD

**Issue by cffycls** [gvcgo/version-manager#6]
powershell已经占用了vm
-------------------------------
PS D:\work> vm list
Get-VM: Hyper-V 找不到名称为“list”的虚拟机

命令提示符正常
-------------------------------
D:\work>vm list

  AppName                                             Homepage
 ‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑
  agg                                                 https://github.com/asciinema/agg
  bun                                                 https://bun.sh
  cmdtools                                            https://developer.android.google.cn/tools/releases/cmdline-tools
  coursier                                            https://get-coursier.io/
  cygwin                                              https://www.cygwin.com/
  deno                                                https://deno.com/
  dotnet                                              https://dotnet.microsoft.com/
  fd                                                  https://github.com/sharkdp/fd
  flutter                                             https://flutter.dev/
  fzf                                                 https://github.com/junegunn/fzf
  git                                                 https://gitforwindows.org/
  gleam                                               https://gleam.run/
  glow                                                https://github.com/charmbracelet/glow
  go                                                  https://go.dev/
  gradle                                              https://gradle.org/

Press "↑/k" to move up, "↓/j" to move down, "q" to quit.

**Comment by moqsien** [comment]
哦，开了hyper-V就有冲突是吧。
之前在我的机器上没发现这个，应该是没开hyper-V。

暂时可以把vm.exe重命名，或者手动建一个vmm.exe之类的软连接/硬连接，把这个连接的路径加到环境变量。vm.exe不要加到环境变量就好了。

后面发新版会把这个考虑进去的。

**Comment by moqsien** [comment]
新版0.1.4已经发布。修复了这个问题。
vm在安装时，会检测Hyper-V是否开启，如果已开启，则自动重命名vm.exe为vmr.exe，用户直接使用vmr命令即可。
如果未开启Hyper-V，那么仍和以前一样，使用vm命令。
