### ISSUE TITLE
在新建的shell中需要重复的安装已经装过的SDK

### ISSUE THREAD

**Issue by Jacky-YC** [gvcgo/version-manager#60]
![image](https://github.com/gvcgo/version-manager/assets/42370375/482e2ca2-677b-4592-9e18-a5a72ba90928)

**Comment by moqsien** [comment]
没有复现你的问题。

但是，有一点需要注意。vmr只能识别通过vmr安装的SDK，通过其他方式安装的SDK种类太多，无法识别。
另外，需要确保SDK已通过vmr安装成功。这一点，可以去~/.vmr/versions/下面确认。

**Comment by Jacky-YC** [comment]
> 没有复现你的问题。
> 
> 但是，有一点需要注意。vmr只能识别通过vmr安装的SDK，通过其他方式安装的SDK种类太多，无法识别。 另外，需要确保SDK已通过vmr安装成功。这一点，可以去~/.vmr/versions/下面确认。

![image](https://github.com/gvcgo/version-manager/assets/42370375/9e41d351-ee73-4adf-90bd-570e78fc50ef)

因为都是通过 vmr 进行安装的，新建的shell PATH中没有对应SDK的配置，所以无法使用。

我不太明白 vmr 的环境变量配置部分，从文档中也无法了解更加详细的设计细节

**Comment by moqsien** [comment]
> > 没有复现你的问题。
> > 但是，有一点需要注意。vmr只能识别通过vmr安装的SDK，通过其他方式安装的SDK种类太多，无法识别。 另外，需要确保SDK已通过vmr安装成功。这一点，可以去~/.vmr/versions/下面确认。
> 
> ![image](https://private-user-images.githubusercontent.com/42370375/339623357-9e41d351-ee73-4adf-90bd-570e78fc50ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzY5NjYsIm5iZiI6MTcxODMzNjY2NiwicGF0aCI6Ii80MjM3MDM3NS8zMzk2MjMzNTctOWU0MWQzNTEtZWU3My00YWRmLTkwYmQtNTcwZTc4ZmM1MGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAzNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOGI4OWM1NTBmMWY0NTRlODg4NTMxNTFlZWE4MTI0ZjU5MzlhODA5MTI3M2Y0MDdhMzNjMWY0YzMwYmVkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TAu-6iQDRTx5K1HLV4GtBi_p5fwhJPtCgLMqQiD8plQ)
> 
> 因为都是通过 vmr 进行安装的，新建的shell PATH中没有对应SDK的配置，所以无法使用。
> 
> 我不太明白 vmr 的环境变量配置部分，从文档中也无法了解更加详细的设计细节

对于zsh，vmr的环境变量放在~/.vmr/vmr.sh，然后在~/.zshrc中引用vmr.sh。
这一点文档中有，在FAQs中，https://gvcgo.github.io/vdocs/#/zh-cn/faq。

**Comment by moqsien** [comment]
如果你首次安装SDK，使用的是session模式，那么不会永久加入环境变量。后面在local installed列表中use一下就行了。具体看界面上的key map提示。

**Comment by Jacky-YC** [comment]
> 如果你首次安装SDK，使用的是session模式，那么不会永久加入环境变量。后面在local installed列表中use一下就行了。具体看界面上的key map提示。

```shell
vmr version

v0.6.2(02c4dcd)
```

session模式是什么？

删除所有vmr安装的maven信息，重新安装没有看到需要我操作的提示。
![image](https://github.com/gvcgo/version-manager/assets/42370375/41ba8a5a-c683-4b53-854c-4306ea1e506f)

安装完成后，新建一个shell ，无法使用刚刚安装的 `mvn` 命令
![image](https://github.com/gvcgo/version-manager/assets/42370375/c5caedcd-ad36-4666-ba5d-4d15f8e2c97d)

**Comment by moqsien** [comment]
把你的~/.vmr/vmr.sh的内容粘贴出来，
另外，看看你的.zshrc文件中，是否有以下内容：
```bash
# vm_envs start
if [ -z "$VM_DISABLE" ]; then
    . ~/.vmr/vmr.sh
fi
# vm_envs end
```

另外，无需新建shell，执行source .zshrc就能刷新环境变量。

**Comment by Jacky-YC** [comment]
> > > 没有复现你的问题。
> > > 但是，有一点需要注意。vmr只能识别通过vmr安装的SDK，通过其他方式安装的SDK种类太多，无法识别。 另外，需要确保SDK已通过vmr安装成功。这一点，可以去~/.vmr/versions/下面确认。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/42370375/339623357-9e41d351-ee73-4adf-90bd-570e78fc50ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzY5NjYsIm5iZiI6MTcxODMzNjY2NiwicGF0aCI6Ii80MjM3MDM3NS8zMzk2MjMzNTctOWU0MWQzNTEtZWU3My00YWRmLTkwYmQtNTcwZTc4ZmM1MGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAzNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOGI4OWM1NTBmMWY0NTRlODg4NTMxNTFlZWE4MTI0ZjU5MzlhODA5MTI3M2Y0MDdhMzNjMWY0YzMwYmVkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TAu-6iQDRTx5K1HLV4GtBi_p5fwhJPtCgLMqQiD8plQ)
> > 因为都是通过 vmr 进行安装的，新建的shell PATH中没有对应SDK的配置，所以无法使用。
> > 我不太明白 vmr 的环境变量配置部分，从文档中也无法了解更加详细的设计细节
> 
> 对于zsh，vmr的环境变量放在~/.vmr/vmr.sh，然后在~/.zshrc中引用vmr.sh。 这一点文档中有，在FAQs中，[https://gvcgo.github.io/vdocs/#/zh-cn/faq。](https://gvcgo.github.io/vdocs/#/zh-cn/faq%E3%80%82)

我在 .zshrc 中找到了这个

![image](https://github.com/gvcgo/version-manager/assets/42370375/3d8452e3-d4fb-4d1f-9bcc-201a9b41ea8c)

![image](https://github.com/gvcgo/version-manager/assets/42370375/8b3dfed3-f9c3-43fa-8d1d-f5d6609c5001)

**Comment by moqsien** [comment]
![微信截图_20240614123634](https://github.com/gvcgo/version-manager/assets/34511192/33d48b6d-2b9c-408d-a019-e4c3101d232d)
1 全局模式安装
2 session模式安装

session模式安装不会永久加入环境变量。注意看提示。

**Comment by Jacky-YC** [comment]
> 把你的~/.vmr/vmr.sh的内容粘贴出来， 另外，看看你的.zshrc文件中，是否有以下内容：
> 
> ```shell
> # vm_envs start
> if [ -z "$VM_DISABLE" ]; then
>     . ~/.vmr/vmr.sh
> fi
> # vm_envs end
> ```
> 
> 另外，无需新建shell，执行source .zshrc就能刷新环境变量。

```shell
.vmr cat ~/.vmr/vmr.sh
# cd hook start
if [ -z "$(alias|grep cdhook)" ]; then
	cdhook() {
		if [ $# -eq 0 ]; then
			cd
		else
			cd "$@" && vmr use -E
		fi
	}
	alias cd='cdhook'
fi
# cd hook end

export PATH=~/.vmr:$PATH

# cd hook start
if [ -z "$(alias|grep cdhook)" ]; then
	cdhook() {
		if [ $# -eq 0 ]; then
			cd
		else
			cd "$@" && vmr use -E
		fi
	}
	alias cd='cdhook'
fi
# cd hook end

export PATH=~/.vmr:$PATH%
```

我很好奇为什么这个文件中内容会重复两次

这导致我的PATH产生很多冗余

`/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr/versions/maven_versions/maven-3.9.7/bin:/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr`

**Comment by moqsien** [comment]
无法重复你的问题。
```bash
export PATH=~/.vmr:$PATH%
```
最后的%也很奇怪。没其他人出现过这样的问题，从代码上也看不出会出现这样的问题。
你可以vmr-uninstall之后，重新安装试试。

**Comment by Jacky-YC** [comment]
> ![微信截图_20240614123634](https://private-user-images.githubusercontent.com/34511192/339636602-33d48b6d-2b9c-408d-a019-e4c3101d232d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDA2ODgsIm5iZiI6MTcxODM0MDM4OCwicGF0aCI6Ii8zNDUxMTE5Mi8zMzk2MzY2MDItMzNkNDhiNmQtMmI5Yy00MDhkLWEwMTktZTRjMzEwMWQyMzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA0NDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjVkNWUyOWZmY2M3ZjAwMTgzZjQ3MWM3OWU1OGM2ODBhODQxNTA5ZDhlNzE0ZmVkYzJkNGI3YWViMmZjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rt5dnvpVmGBtT65hZJV4OeKtm7A_c9iVu7FojKKUXGo) 1 全局模式安装 2 session模式安装
> 
> session模式安装不会永久加入环境变量。注意看提示。

😯，我明白了，我在选中对应SDK版本的时候用 `s` 进行安装，这导致它只在当前shell中生效；

对于全局安装应使用 `i` 选项进行安装。

我跟着 [gallery](https://gvcgo.github.io/vdocs/#/gallery)  进行操作，没有理解这个意思。

很抱歉，给你添了不必要的麻烦。

**Comment by moqsien** [comment]
> > ![微信截图_20240614123634](https://private-user-images.githubusercontent.com/34511192/339636602-33d48b6d-2b9c-408d-a019-e4c3101d232d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDA2ODgsIm5iZiI6MTcxODM0MDM4OCwicGF0aCI6Ii8zNDUxMTE5Mi8zMzk2MzY2MDItMzNkNDhiNmQtMmI5Yy00MDhkLWEwMTktZTRjMzEwMWQyMzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA0NDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjVkNWUyOWZmY2M3ZjAwMTgzZjQ3MWM3OWU1OGM2ODBhODQxNTA5ZDhlNzE0ZmVkYzJkNGI3YWViMmZjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rt5dnvpVmGBtT65hZJV4OeKtm7A_c9iVu7FojKKUXGo) 1 全局模式安装 2 session模式安装
> > session模式安装不会永久加入环境变量。注意看提示。
> 
> 😯，我明白了，我在选中对应SDK版本的时候用 `s` 进行安装，这导致它只在当前shell中生效；
> 
> 对于全局安装应使用 `i` 选项进行安装。
> 
> 我跟着 [gallery](https://gvcgo.github.io/vdocs/#/gallery) 进行操作，没有理解这个意思。
> 
> 很抱歉，给你添了不必要的麻烦。

没事。gallery不是教程，只是一个基本演示，而且没有具体按键显示，不要当做实际参考。
具体要看key map中的英文提示。

**Comment by moqsien** [comment]
> > 把你的~/.vmr/vmr.sh的内容粘贴出来， 另外，看看你的.zshrc文件中，是否有以下内容：
> > ```shell
> > # vm_envs start
> > if [ -z "$VM_DISABLE" ]; then
> >     . ~/.vmr/vmr.sh
> > fi
> > # vm_envs end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外，无需新建shell，执行source .zshrc就能刷新环境变量。
> 
> ```shell
> .vmr cat ~/.vmr/vmr.sh
> # cd hook start
> if [ -z "$(alias|grep cdhook)" ]; then
> 	cdhook() {
> 		if [ $# -eq 0 ]; then
> 			cd
> 		else
> 			cd "$@" && vmr use -E
> 		fi
> 	}
> 	alias cd='cdhook'
> fi
> # cd hook end
> 
> export PATH=~/.vmr:$PATH
> 
> # cd hook start
> if [ -z "$(alias|grep cdhook)" ]; then
> 	cdhook() {
> 		if [ $# -eq 0 ]; then
> 			cd
> 		else
> 			cd "$@" && vmr use -E
> 		fi
> 	}
> 	alias cd='cdhook'
> fi
> # cd hook end
> 
> export PATH=~/.vmr:$PATH%
> ```
> 
> 我很好奇为什么这个文件中内容会重复两次
> 
> 这导致我的PATH产生很多冗余
> 
> `/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr/versions/maven_versions/maven-3.9.7/bin:/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr:/Users/jacky/.vmr`

上面的vmr.sh中的重复部分可以删去。这个应该是某种未知情况下出现的，重复不出来。

至于下面echo $PATH出现重复，应该是因为你多次使用session模式，导致嵌套开了很多个session，session之间有环境变量集成，造成重复，这无所谓。只要所有session退出之后就没有了。

**Comment by zzhaolei** [comment]
cat 显示的末尾的 % 是应该是文件在此处结束了，没有结束符，这个不会影响脚本的运行。它的出现应该和 vmr.sh 的内容重复有关

**Comment by moqsien** [comment]
> cat 显示的末尾的 % 是应该是文件在此处结束了，没有结束符，这个不会影响脚本的运行。它的出现应该和 vmr.sh 的内容重复有关

不太明白，重复是怎么来的。按道理，有检测重复的，如果存在就不会再添加了。不知道这是什么情况下出现的。

**Comment by zzhaolei** [comment]
重复检测有问题，如果用户执行了多次 vmr i 进行安装，则会出现重复，我来提个 PR 优化一下这个检测

**Comment by moqsien** [comment]
> 重复检测有问题，如果用户执行了多次 vmr i 进行安装，则会出现重复，我来提个 PR 优化一下这个检测

好的，辛苦。

**Comment by moqsien** [comment]
vmr.sh出现重复已修复。
详见[release](https://github.com/gvcgo/version-manager/releases/tag/v0.6.2)。
@Jacky-YC 

感谢 @zzhaolei
