### ISSUE TITLE
为什么安装脚本写死了走代理地址

### ISSUE THREAD

**Issue by 96368a** [gvcgo/version-manager#62]
安装脚本
[https://raw.githubusercontent.com/gvcgo/version-manager/main/scripts/install.sh](https://raw.githubusercontent.com/gvcgo/version-manager/main/scripts/install.sh)
里面的download_url变量写死了
`https://gvc.1710717.xyz/proxy/https://github.com/gvcgo/version-manager/releases/download/`

**Comment by moqsien** [comment]
已修复。
