### ISSUE TITLE
no sdk found

### ISSUE THREAD

**Issue by coosir** [gvcgo/version-manager#63]
➜  ~ vmr
 WARNING  no sdk found!
➜  ~ vmr version
v0.6.2(5d39224)

just drive me crazy...

**Comment by coosir** [comment]
related with this?

curl --proto '=https' -sSf https://gvc.1710717.xyz/proxy/https://raw.githubusercontent.com/gvcgo/version-manager/main/scripts/install.preview.sh
curl: (22) The requested URL returned error: 502

**Comment by moqsien** [comment]
https://gvcgo.github.io/vdocs/#/zh-cn/usage?id=%e8%ae%be%e7%bd%ae%e4%bb%a3%e7%90%86
