### ISSUE TITLE
不支持直接从源下载

### ISSUE THREAD

**Issue by ylx252** [gvcgo/version-manager#64]
不支持直接重源下载，类似pyenv执行源可以直接下载python
https://mirrors.huaweicloud.com/python/
https://cdn.npmmirror.com/binaries/python/
https://npm.taobao.org/mirrors/python/

**Comment by moqsien** [comment]
vmr目前不支持从源码编译。python的这些下载源，除了windows是exe，其他都是源码，需要编译。

vmr目前对于这些需要编译的SDK，走的是Anaconda的conda-forge源，同样是安全可信的。
