### ISSUE TITLE
为啥必须要使用cd命令后才会切换版本呢

### ISSUE THREAD

**Issue by anganing** [gvcgo/version-manager#67]
这个直接打开是不行的，必须cd命令进来才会切换
![image](https://github.com/gvcgo/version-manager/assets/63218247/5bee4dbb-90cd-41df-a527-208ced6c2672)

nvmd可以在打开终端就是切换版本了：
https://github.com/1111mp/nvm-desktop/releases

大佬可否参考一下这个的设计，以及出个图形化管理的客户端呢，命令行有时候方便但对于新手GUI更友好。
文档使用方法建议详细一点，图文并茂举一个使用例子（例如，node,java等）最好（特别是针对项目锁定版本），不然很劝退新手。
我只是提个建议哈，好东西要更多人用起来嘛！

**Comment by moqsien** [comment]
1. GUI目前不考虑。因为上GUI太笨重了，VMR的初衷就是命令行工具。而且目前已经有了非常直观得TUI(Terminal UI)，这一点已经远强于绝大多数SDK版本管理器了。
2. VSCode打开项目，集成终端即自动切换到锁定的SDK版本，这一功能已经在v0.6.3中实现。使用vmr-update命令更新即可体验。(其他IDE尚未测试，因为我手头没有，推测应该都可以。)
