### ISSUE TITLE
Can not search erlang sdk

### ISSUE THREAD

**Issue by fluent12138** [gvcgo/version-manager#68]
1. my window10 pc running  wsl system
$ wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2

2. my wsl system version info
root# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

3. run vmr to search erlang, and it return this result
root@LAPTOP-IUKO3FRG:~# vmr
  INFO    No versions found for current platform.
  
I don’t know if this is due to my WSL environment or a Vmr issue, because I installed Elixir or other language SDKs normally. Please take a look at this problem.

**Comment by fluent12138** [comment]
On my Alibaba Cloud server, I also can’t find Erlang in the Ubuntu 20.04 version.

root:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by moqsien** [comment]
vmr does support native installations of erlang/elixir for windows, you do not need to use WSL.

BTW, it seems that there is sth. wrong with the version list of erlang, I'll work it later. Thanks for your feedback.

**Comment by moqsien** [comment]
Already fixed.
