### ISSUE TITLE
能否尽快追上支持各SDK的最新版本或者如何开放贡献让大家来支持

### ISSUE THREAD

**Issue by xflcx1991** [gvcgo/version-manager#7]
比如 Bun 已经到1.1了，但是sdk搜索的还是1.0.x。是否开放贡献，让大家来支持最新版本。

**Comment by moqsien** [comment]
> 比如 Bun 已经到1.1了，但是sdk搜索的还是1.0.x。是否开放贡献，让大家来支持最新版本。

为了维持稳定性和可用性，爬虫部分剥离了。每天会向仓库同步至少两次最新版本。一般来说，延迟不会超过12小时。这样的更新频率，已经可以满足绝大多数场景了。

**Comment by moqsien** [comment]
![vm_bun](https://github.com/gvcgo/version-manager/assets/34511192/016de0d9-dfbe-41e4-90ef-8a8f839d161b)

已是最新。

**Comment by moqsien** [comment]
感觉bun有点奇葩，都到1.0以上稳定版本了，反而越发越快，这不科学啊。

**Comment by xflcx1991** [comment]
谢谢，我明白了
