### ISSUE TITLE
使用 pscore 开启 vmr 之后，会自动切换到 ps

### ISSUE THREAD

**Issue by devbean** [gvcgo/version-manager#70]
在 Windows 平台，使用 pscore 开启`vmr`之后，运行 use 命令：`vmr use -E node:20.15.0`，会启动切换回 Windows 自带 powershell 版本，而不是返回 pscore，看起来是新开了一个终端：
![PixPin_2024-06-27_10-18-14](https://github.com/gvcgo/version-manager/assets/1142097/20b02ad4-1923-4122-a2ec-0d68b81f2091)

**Comment by moqsien** [comment]
这是正常的。
1. 所有的临时的版本切换（指所有不影响全局版本的情况），都是新建一个终端会话，把需要的版本的环境变量加入这个新的会话中。
2. 不是所有机器都安装了最新的pscore，所以默认是以powershell来开启新的会话。一个可能行得通的方案：用户可以自行设置别名，把powershell这个命令指向pscore，这样vmr就会使用pscore来创建新的会话了。

**Comment by moqsien** [comment]
不过也可以增加一下自动检测。后面可以考虑增加。

**Comment by moqsien** [comment]
想了下，比较简单。已更新。
使用vmr-update命令更新一下即可。
