### ISSUE TITLE
jdk不能安装GraalVM JDK

### ISSUE THREAD

**Issue by Zhangxxl** [gvcgo/version-manager#71]
无法安装GraalVM, 另外建议增加其他厂商维护的jdk供用户选择, 比如如下这些:
GraalVM JDK
Temurin Jdk
AdoptOpenJDK
Azul Zulu Jdk
BellSoft Liberica JDK
Amazon Corretto JDK
Microsoft  OpenJDK
Alibaba Dragonwell JDK
Red Hat OpenJDK

**Comment by moqsien** [comment]
方便解释一下么，
我一直也很好奇，这么多JDK发行版，在开发时有什么区别？
有没有这样的情况，某个项目代码只能在指定的JDK发行版上运行？

因为我不做Java开发，所以有此一问，单纯好奇。

另外，如果某个发行版对于java开发而言不是必须的，那么vmr考虑还是维持相对支持完善的单一发行版。
如果确有其必须之处，后面再考虑支持。

**Comment by chengpopeye** [comment]
![image](https://github.com/gvcgo/version-manager/assets/40633896/0819e814-14ae-4ba8-a082-32735eccad42)

**Comment by chengpopeye** [comment]
1.是否收费2.不同公司是否对jdk进行修改扩展功能和性能优化
![image](https://github.com/gvcgo/version-manager/assets/40633896/c29354d4-8453-44fa-a210-abffcccfaa08)

**Comment by chengpopeye** [comment]
1.是否收费 
2.不同公司是否持续 对jdk进行修改扩展功能和性能优化
![image](https://github.com/gvcgo/version-manager/assets/40633896/7c88a044-5cfd-492f-a4bf-a535a7940e71)

**Comment by moqsien** [comment]
如果仅仅是这种区别，那么vmr使用的bellsoft的Liberica发行版，比这些也更好，至少也不差。
重点是，也不影响本地开发。

之前使用的是Adopt发行版，但是一些vmr用户反馈Adopt发行版的低版本不支持Apple M芯片，所以切换到支持更全面的Liberica。

https://bell-sw.com/pages/downloads/

可以看到，Liberica支持的比很多发行版都要全面。

**Comment by Zhangxxl** [comment]
> 如果仅仅是这种区别，那么vmr使用的bellsoft的Liberica发行版，比这些也更好，至少也不差。 重点是，也不影响本地开发，就没必要搞这么多发行版。
> 
> 之前使用的是Adopt发行版，但是一些vmr用户反馈Adopt发行版的低版本不支持Apple M芯片，所以切换到支持更全面的Liberica。
> 
> https://bell-sw.com/pages/downloads/
> 
> 可以看到，Liberica支持的比很多发行版都要全面。Liberica还支持LibericaFX，OpenJFX.

虽然大部分jdk功能是大差不差基本一样, 但还是有部分jdk是不一样的, 例如 IBM Semeru JDK 集成了OpenJ9 虚拟机, 这个不同于其他OpenJDK 里的 HotSpot,专注于节省内存.   还有GraalVM JDK, 其他jdk只能编译jar或者class文件, 它附带的GraalVM 编译器可以不光可以把java程序编译jar或者classs, 还能编译成原生操作系统应用或者native-image

**Comment by sgpublic** [comment]
我也希望增加至少三个发行版，并附带理由：

+ [Open JDK](https://openjdk.org/)：官方开源实现，是使用率最高的发行版之一。
+ [GraalVM JDK](https://www.graalvm.org/downloads/)：可用作编译为原生镜像，性能更高。
+ [JetBrains Runtime JDK](https://github.com/JetBrains/JetBrainsRuntime)：拥有针对桌面 GUI 的优化，对 [Compose Desktop](https://github.com/JetBrains/compose-multiplatform) 开发有好处。

希望大佬能再考虑一下这个需求，VMR 项目确实很好用，谢谢大佬！

**Comment by quentingosset** [comment]
@moqsien can you reopening this issue because it is indeed important to offer different versions of JDK. In my example, our company has decided to work with TEMURIN for certain reasons.
I am available to help you create the PR if I can understand how you add “sub-jdk” to your applications.
