### ISSUE TITLE
加个数据库好做吗mysql什么的

### ISSUE THREAD

**Issue by Haif-07** [gvcgo/version-manager#72]

**Comment by moqsien** [comment]
可以，但是觉得数据库这种没必要做版本管理吧？

**Comment by chengpopeye** [comment]
做Java的，个人认为有必须，可以MySQL5.x和MySQL8.x版本
老点的项目使用MySQL5.x版本，新项目一般MySQL8.x版本

**Comment by moqsien** [comment]
我的意思是，公司都有测试库的，谁还在本地安装数据库？

**Comment by Haif-07** [comment]
> 可以，但是觉得数据库这种没必要做版本管理吧？

ooh，可能我的表达不对，我更多的是把这个当做一个方便安装的工具了而不是版本管理。能一个命令安装完感觉很方便

**Comment by moqsien** [comment]
如果需求比较多，
MySQL，PostgreSQL，MongoDB，Pika等都可以做。

**Comment by moqsien** [comment]
> > 可以，但是觉得数据库这种没必要做版本管理吧？
> 
> ooh，可能我的表达不对，我更多的是把这个当做一个方便安装的工具了而不是版本管理。能一个命令安装完感觉很方便

已支持MySQL和PostgreSQL，但是安装完成之后，还是需要自己配置数据库文件目录，账号等等信息的。
MySQL和PostgreSQL都是通过conda安装，具体如何配置使用，请自行搜索教程。
