### ISSUE TITLE
windows系统的可以出一个新手教程吗？ 环境有问题vmr list Error: unknown command "list" for "vmr" Run 'vmr --help' for usage.

### ISSUE THREAD

**Issue by chengpopeye** [gvcgo/version-manager#73]
问题1： vmr list
Error: unknown command "list" for "vmr"
Run 'vmr --help' for usage.
问题2：加了代理有查看代理的命令吗
加入代理没看到sdk的版本列表

**Comment by moqsien** [comment]
请认真阅读文档https://vdocs.vmr.us.kg/zh-cn/，文档内容适用于支持的任何系统！

**Comment by chengpopeye** [comment]
看了没解决我的问题

**Comment by chengpopeye** [comment]
新手搞个视频最直观了，powershell刷新的命令我是真不知道是什么，我是直接重新电脑的

**Comment by chengpopeye** [comment]
新手搞个视频最直观了，没有用过powershell刷新的命令我是真不知道是什么，我是直接重新电脑的
我看了bilibili的视频，一样的操作就是 vmr list
Error: unknown command "list" for "vmr"
Run 'vmr --help' for usage.

这个环境变量需要手动配置的吗
