### ISSUE TITLE
vmr安装的Python版本，不能被安装程序识别

### ISSUE THREAD

**Issue by ahwgit** [gvcgo/version-manager#75]
我用vmr下载了几个Python版本，并把其中一个版本3.9.16作为全局版本（查看到环境变量已自动添加好了），
然后安装devicetool-windows-tool-4.0.0.400.exe（是华为鸿蒙的设备开发程序，会以插件的形式显示在VSCode里），
却提示找不到Python3.8/3.9(安装程序需要Python3.9或者3.8环境)，

我单独安装从官网下载的Python3.9或3.8  .exe文件，它却能识别到，不知道是哪里的问题？我是在win11下操作的

**Comment by moqsien** [comment]
听描述，感觉跟devicetool-windows-tool-4.0.0.400.exe的检测方式有关。如果它是按安装路径来检测的，估计就只能识别安装在官方默认路径下面的Python。你可以检索一下，是否支持指定python编译器路径，将它指定为vmr的python安装路径即可。

**Comment by moqsien** [comment]
这个估计没办法。
看了下，没想到大厂出品的东西还这么蠢，完全是靠写死的路径来检测的Python，而不是靠环境变量。

也不给个自定义的输入框作为选择。尽显大厂的傲慢。

**Comment by moqsien** [comment]
我已经向华为开发者论坛反映和吐槽了。看他们是继续保持傲慢，还是虚心改进吧。

**Comment by ahwgit** [comment]
感谢辛苦回复！我再试试

**Comment by moqsien** [comment]
没啥。多推广一下vmr，带人来给vmr点star就行了
^_^

**Comment by ahwgit** [comment]
已在华为开发者论坛推广了vmr链接，好东西要更多的人参与
