### ISSUE TITLE
After installing go and node on windows, go and node cannot be used

### ISSUE THREAD

**Issue by Avey777** [gvcgo/version-manager#77]
![image](https://github.com/gvcgo/version-manager/assets/35259040/9dac33ba-cabc-4aaf-810d-5327b8866693)
![image](https://github.com/gvcgo/version-manager/assets/35259040/ba25309c-bb8b-4557-9b0e-5b04cb71334c)
------
![image](https://github.com/gvcgo/version-manager/assets/35259040/99893d10-edbe-4ac8-a9a7-d3a0e2b83b87)
![image](https://github.com/gvcgo/version-manager/assets/35259040/f6d3999e-7312-48e4-abda-648dc4a2f31b)
It should be an environment variable configuration problem

**Comment by moqsien** [comment]
read the docs.
https://vdocs.vmr.us.kg/guides/faq/#need-to-refresh-the-envs-for-current-terminal-session
