### ISSUE TITLE
pypy版本安装到Python版本文件夹里面去了

### ISSUE THREAD

**Issue by ahwgit** [gvcgo/version-manager#79]
刚才安装了pypy的两个版本7.3.15和7.3.13，查看了一下都在python_versions里面，另外生成的pypy_versions文件夹是空的，好奇怪！

然后我又用vmr命令行列出本地安装的pypy所有版本，返回信息是没有安装pypy。这肯定是有问题了。

然后我想删除安装的所有pypy（按r），结果删不掉了，怎么办？

**Comment by moqsien** [comment]
pypy安装到python_versions是正常设计，因为pypy的sdk命令也是python。
但是卸载方面确实存在一个隐藏bug，已经修复。使用vmr-update更新即可。
修复之后，可以正常显示已安装的pypy，以及卸载pypy。

**Comment by ahwgit** [comment]
谢谢已修复，没问题了。

可以弄个版本软连接到pypy_versions，这样就不别扭了，哈哈😄
