### ISSUE TITLE
无法正常安装

### ISSUE THREAD

**Issue by devhub126** [gvcgo/version-manager#8]
执行:
```shell
vm is 
```
提示:
```shell
'get-vm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```

**Comment by moqsien** [comment]
复制命令安装。或者

写完整路径path\to\vm.exe is。

**Comment by devhub126** [comment]
> 复制命令安装。或者
> 
> 写完整路径path\to\vm.exe is。

![image](https://github.com/gvcgo/version-manager/assets/153571978/53348231-cb67-4883-8259-fdeed9574992)
还是不行
