### ISSUE TITLE
feat request: 希望添加 c++ 支持，并改善 dlang 支持

### ISSUE THREAD

**Issue by ClHg2** [gvcgo/version-manager#81]
## Platform Info

Ubuntu 20.04.

## Description

1. 希望支持 g++，我猜这个和 gcc 差不多。
2. dlang 有三个编译器，我试了一下好像只支持 dmd，希望能支持 gdc。

已经 star（大雾）

**Comment by moqsien** [comment]
https://stackoverflow.com/questions/172587/what-is-the-difference-between-g-and-gcc

1. 精力有限，暂时不考虑单独支持g++(几乎等价于gcc -xc++ -lstdc++ -shared-libgcc)。
2. gdc只是gcc的一个dlang前端，目前不方便支持。
