### ISSUE TITLE
tree-sitter安装失败

### ISSUE THREAD

**Issue by ahwgit** [gvcgo/version-manager#84]
## Platform Info

win11PWS i7-10750h
## Description

连续安装了最前面三个版本，均报错。
## Screen Shot

![tree-sitter-windows-x64 err](https://github.com/gvcgo/version-manager/assets/131632715/e7e02228-898c-4fb5-aeac-1c93c3e2a7ad)

**Comment by moqsien** [comment]
fixed.

**Comment by ahwgit** [comment]
感谢！
