### ISSUE TITLE
开启镜像，下载node会失败

### ISSUE THREAD

**Issue by ahwgit** [gvcgo/version-manager#86]
## Platform Info

win11PWS i7-10750h
## Description

昨天晚上打开配置conf的时候发现镜像是关闭的，于是我把UseCustomedMirrors = true（应该下载会快一点），结果node-v20.15.1下载报错、失败，但是node-v20.15.0下载成功。
今天早上我又把UseCustomedMirrors = false，node-v20.15.1下载成功。
这是不是说明镜像设置项是有一点问题的？（镜像文件没有改动过，线程都是1，vmr st 1）
--------
镜像不仅没起到加速的作用，反而是在“拖后腿”，今天pip一直升级失败，关闭镜像就升级成功了

## Screen Shot

![UseCustomedMirrors = true](https://github.com/gvcgo/version-manager/assets/131632715/cc8dce3e-b382-465c-b7cd-699ce417abc0)

![UseCustomedMirrors = false](https://github.com/gvcgo/version-manager/assets/131632715/fd41e933-1daa-44a6-ae7b-4db5fcc54260)

**Comment by moqsien** [comment]
无法重复。
