### ISSUE TITLE
是不是网站出问题了，我咋访问不了 你们网站。。

### ISSUE THREAD

**Issue by snail2sky** [gvcgo/version-manager#87]
## Screen Shot

直接给我reset了，难道是被墙了？
![image](https://github.com/gvcgo/version-manager/assets/49757958/8a1442cd-0c87-40dc-9468-96991524e10e)

**Comment by moqsien** [comment]
![docs_site](https://github.com/user-attachments/assets/9581ee0b-8eb1-4b7b-8d98-fb828eec0114)
