### ISSUE TITLE
为 `search` 子命令添加一个按键事件能直接安装对应的 sdk

### ISSUE THREAD

**Issue by fzdwx** [gvcgo/version-manager#9]
目前 `search` 出来的 tui 只能上下移动以及 `enter` 后复制版本号，可以添加一个 `i` 按键事件，直接下载并 `use` ? 理论是上是可以实现的, 如果你同意这个提议，我这这几天会将它实现。

**Comment by moqsien** [comment]
> 目前 `search` 出来的 tui 只能上下移动以及 `enter` 后复制版本号，可以添加一个 `i` 按键事件，直接下载并 `use` ? 理论是上是可以实现的, 如果你同意这个提议，我这这几天会将它实现。

目前增加了复制到剪贴版功能，也就是把已选择的版本号自动加入剪贴板。然后可以在use命令中使用。

我之前想过直接在enter之后触发install事件，但是觉得有时候会导致误操作，而且与use命令重复，感觉体验应该不会特别好。

**我有个想法，就是根据选择，自动生成use命令，由用户去决定是否复制剪贴板命令来一键安装对应版本，而且用户也可以对命令进行编辑，决定是否使用session模式。**

你觉得呢？

**Comment by moqsien** [comment]
已更新。

增加自动生成use命令，并添加到系统剪贴板。这样，你要是想安装对应版本，直接ctrl+v或者cmd+v，即可一键安装。
而且，你还可以编辑生成的use命令后，再运行，例如加入-s，开启session模式。
