### ISSUE TITLE
希望加个Ilvm-mingw

### ISSUE THREAD

**Issue by ahwgit** [gvcgo/version-manager#96]
## Platform Info

win11PWS i7-10750h
## Description

LLVM-MinGW 是一个使用 Clang、LLD、libc++ 构建的工具链，针对 i686、x86_64、arm 和 aarch64 (ARM64)，其版本既可以作为交叉编译器从 Linux 运行，也可以在 Windows 上运行。

感觉Ilvm-mingw也要用vmr管理起来才好，https://www.mingw-w64.org/downloads/

![kimi](https://github.com/user-attachments/assets/b51ac9fd-2ca4-407b-be0e-de9540993d00)

**Comment by moqsien** [comment]
已支持。
