### ISSUE TITLE
请求支持通过 Homebrew 安装 VMR

### ISSUE THREAD

**Issue by QuillVot** [gvcgo/version-manager#97]
请求支持通过 Homebrew 安装 VMR
```shell
# 期望这行shell能执行
brew install vmr
```

**Comment by moqsien** [comment]
目前不考虑支持。现有的安装和更新方式已经很简便了。
[文档](https://vdocs.vmr.us.kg/zh-cn/starts/quickstart/#%E6%9B%B4%E6%96%B0)
