### ISSUE TITLE
安装go之后，无法执行go

### ISSUE THREAD

**Issue by tr1gv0n** [gvcgo/version-manager#98]
## Platform Info
windows

## Description
安装其他版本go之后，无法执行go。在环境变量中配置的GOROOT是d:\.vmr\versions\go_versions\go。目前无法找到这个目录。
我的判断：无法执行go的原因是%GOROOT%\bin不存在

## Screen Shot
![image](https://github.com/user-attachments/assets/285b3b95-cd48-40c7-b7cb-1917efaf0d19)

**Comment by moqsien** [comment]
无法重复你的问题。

需要注意：
1. 如果使用全局模式安装，go_versions下面应该有一个名称为go的文件夹软链接，用于指向全局当前使用版本。
2. 如果全部使用非全局模式安装，那么go的Path是不会添加到Windows的PATH变量的。当前Powershell终端退出之后，路径自然失效，下次自然找不到go的路径。这一点注意读文档！！

**Comment by tr1gv0n** [comment]
> 无法重复你的问题。
> 
> 需要注意：
> 
> 1. 如果使用全局模式安装，go_versions下面应该有一个名称为go的文件夹软链接，用于指向全局当前使用版本。
> 2. 如果全部使用非全局模式安装，那么go的Path是不会添加到Windows的PATH变量的。当前Powershell终端退出之后，路径自然失效，下次自然找不到go的路径。这一点注意读文档！！

一直使用全局模式安装，但是在go_versions下面没有go这个文件夹软链接

**Comment by tr1gv0n** [comment]
https://github.com/gvcgo/version-manager/blob/d5f34467fe0163a777407b5a5236b688e9a725bc/internal/installer/installer.go#L91
我本地创建了软链接，使用vmr全局模式切换版本后，软链接目录被删除，执行到了这里
[		utils.CreateSymLink(installDir, symbolPath)](https://github.com/gvcgo/version-manager/blob/d5f34467fe0163a777407b5a5236b688e9a725bc/internal/installer/installer.go#L95)
好像是这里出现了问题，软链接没有建立成功，但是我这边获取不到具体原因。
我的系统是win10专业版22h2

**Comment by moqsien** [comment]
软链接是vmr自动创建的。

但是FAT exFAT FAT32这些格式的盘不支持创建软链接。

**Comment by BleethNie** [comment]
我 ubuntu Ubuntu 22.04.4 LTS版本也是安装了go，无法执行go命令
安装完成后可以执行go命令，但是退出shell窗口后再重新打开shell创建则无法执行go命令

**Comment by moqsien** [comment]
> 我 ubuntu Ubuntu 22.04.4 LTS版本也是安装了go，无法执行go命令 安装完成后可以执行go命令，但是退出shell窗口后再重新打开shell创建则无法执行go命令
> 
> 无法执行go命令 ![image](https://private-user-images.githubusercontent.com/17614992/361859683-10126e1b-4d5e-4c57-b319-1e568c525067.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTY2ODIsIm5iZiI6MTcyNDg1NjM4MiwicGF0aCI6Ii8xNzYxNDk5Mi8zNjE4NTk2ODMtMTAxMjZlMWItNGQ1ZS00YzU3LWIzMTktMWU1NjhjNTI1MDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE0NDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMTFjYjE4Y2JmZWE2ZjMyMzA2MzhkOTk5MzRlYjhhMDdlM2ViOTcwMWZhYzQ0NmFmODdhOTQzYmQxMTJiYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XK3Iva7Xf2KTiZkMHH41X-rMVGF6E2mkZU0UodP06Iw)
> 
> vmr自动安装位置 ![image](https://private-user-images.githubusercontent.com/17614992/361859818-cae46fdf-b386-4e05-bb41-bd624f0e6fdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTY2ODIsIm5iZiI6MTcyNDg1NjM4MiwicGF0aCI6Ii8xNzYxNDk5Mi8zNjE4NTk4MTgtY2FlNDZmZGYtYjM4Ni00ZTA1LWJiNDEtYmQ2MjRmMGU2ZmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE0NDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNWFjNDJhNTIwM2E0NTFkYWE1ZjNlMWZjMjkwMDczMGI4YTkyZTA1YWIzYjBkMjRiMTNlNWEyOGZlNmRhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjeW0q0_wOq97BUgz5dXP5Oq0URIa4MjJ52FGxay5-8)
> 
> golang自动安装位置 ![image](https://private-user-images.githubusercontent.com/17614992/361859969-caafc88d-a9fc-478c-b988-a703272a8a3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTY2ODIsIm5iZiI6MTcyNDg1NjM4MiwicGF0aCI6Ii8xNzYxNDk5Mi8zNjE4NTk5NjktY2FhZmM4OGQtYTlmYy00NzhjLWI5ODgtYTcwMzI3MmE4YTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE0NDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNDdmZmY3NGExOWJkODFjYjM1ZTE4YjdjYzg2ODNkOTYwOTc1ZWI0M2FkY2MyNWM4Y2QzZTFhZDU1NzU0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0O49ouxoZJaXBAZubDHYeHKBEwMLpXMmkbUTuaqsAWc)

注意读文档。
用session模式安装的SDK，不会自动加入PATH。想要假如PATH变量，使用global模式安装。

**Comment by Yuelioi** [comment]
同样不行, 无法在安装后直接在命令行使用go

在powershell/powershell(管理员)/cmd 分别使用了cli(use)和tui(i模式) 都不行

系统是win10 1909刚装的新系统

**Comment by moqsien** [comment]
> 同样不行, 无法在安装后直接在命令行使用go
> 
> 在powershell/powershell(管理员)/cmd 分别使用了cli(use)和tui(i模式) 都不行
> 
> 系统是win10 1909刚装的新系统

windows安装了sdk，当前窗口找不到命令，排查问题步骤：

1、排除session模式安装；
2、使用source命令(vmr为windows用户定制了source命令，用于刷新path环境变量，和unix-like系统类似)，对当前powershell刷新环境变量，或者关闭当前powershell窗口之后重新开一个
3、查看windows系统环境变量，看看PATH中是否有加入相应的路径
